/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.fsoft.bn.model.impl;

import com.fsoft.bn.model.AnswerAttachedFile;
import com.fsoft.bn.model.AnswerAttachedFileModel;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the AnswerAttachedFile service. Represents a row in the &quot;BN_AnswerAttachedFile&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.fsoft.bn.model.AnswerAttachedFileModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link AnswerAttachedFileImpl}.
 * </p>
 *
 * @author FSOFT
 * @see AnswerAttachedFileImpl
 * @see com.fsoft.bn.model.AnswerAttachedFile
 * @see com.fsoft.bn.model.AnswerAttachedFileModel
 * @generated
 */
public class AnswerAttachedFileModelImpl extends BaseModelImpl<AnswerAttachedFile>
	implements AnswerAttachedFileModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a answer attached file model instance should use the {@link com.fsoft.bn.model.AnswerAttachedFile} interface instead.
	 */
	public static final String TABLE_NAME = "BN_AnswerAttachedFile";
	public static final Object[][] TABLE_COLUMNS = {
			{ "answer_attached_id", Types.VARCHAR },
			{ "answer_id", Types.VARCHAR },
			{ "attached_file_id", Types.VARCHAR },
			{ "created_date", Types.TIMESTAMP },
			{ "modified_date", Types.TIMESTAMP },
			{ "deleted", Types.BOOLEAN }
		};
	public static final String TABLE_SQL_CREATE = "create table BN_AnswerAttachedFile (answer_attached_id VARCHAR(75) not null primary key,answer_id VARCHAR(75) null,attached_file_id VARCHAR(75) null,created_date DATE null,modified_date DATE null,deleted BOOLEAN)";
	public static final String TABLE_SQL_DROP = "drop table BN_AnswerAttachedFile";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.fsoft.bn.model.AnswerAttachedFile"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.fsoft.bn.model.AnswerAttachedFile"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.fsoft.bn.model.AnswerAttachedFile"));

	public AnswerAttachedFileModelImpl() {
	}

	public String getPrimaryKey() {
		return _answer_attached_id;
	}

	public void setPrimaryKey(String primaryKey) {
		setAnswer_attached_id(primaryKey);
	}

	public Serializable getPrimaryKeyObj() {
		return _answer_attached_id;
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey((String)primaryKeyObj);
	}

	public Class<?> getModelClass() {
		return AnswerAttachedFile.class;
	}

	public String getModelClassName() {
		return AnswerAttachedFile.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("answer_attached_id", getAnswer_attached_id());
		attributes.put("answer_id", getAnswer_id());
		attributes.put("attached_file_id", getAttached_file_id());
		attributes.put("created_date", getCreated_date());
		attributes.put("modified_date", getModified_date());
		attributes.put("deleted", getDeleted());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		String answer_attached_id = (String)attributes.get("answer_attached_id");

		if (answer_attached_id != null) {
			setAnswer_attached_id(answer_attached_id);
		}

		String answer_id = (String)attributes.get("answer_id");

		if (answer_id != null) {
			setAnswer_id(answer_id);
		}

		String attached_file_id = (String)attributes.get("attached_file_id");

		if (attached_file_id != null) {
			setAttached_file_id(attached_file_id);
		}

		Date created_date = (Date)attributes.get("created_date");

		if (created_date != null) {
			setCreated_date(created_date);
		}

		Date modified_date = (Date)attributes.get("modified_date");

		if (modified_date != null) {
			setModified_date(modified_date);
		}

		Boolean deleted = (Boolean)attributes.get("deleted");

		if (deleted != null) {
			setDeleted(deleted);
		}
	}

	public String getAnswer_attached_id() {
		if (_answer_attached_id == null) {
			return StringPool.BLANK;
		}
		else {
			return _answer_attached_id;
		}
	}

	public void setAnswer_attached_id(String answer_attached_id) {
		_answer_attached_id = answer_attached_id;
	}

	public String getAnswer_id() {
		if (_answer_id == null) {
			return StringPool.BLANK;
		}
		else {
			return _answer_id;
		}
	}

	public void setAnswer_id(String answer_id) {
		_answer_id = answer_id;
	}

	public String getAttached_file_id() {
		if (_attached_file_id == null) {
			return StringPool.BLANK;
		}
		else {
			return _attached_file_id;
		}
	}

	public void setAttached_file_id(String attached_file_id) {
		_attached_file_id = attached_file_id;
	}

	public Date getCreated_date() {
		return _created_date;
	}

	public void setCreated_date(Date created_date) {
		_created_date = created_date;
	}

	public Date getModified_date() {
		return _modified_date;
	}

	public void setModified_date(Date modified_date) {
		_modified_date = modified_date;
	}

	public boolean getDeleted() {
		return _deleted;
	}

	public boolean isDeleted() {
		return _deleted;
	}

	public void setDeleted(boolean deleted) {
		_deleted = deleted;
	}

	@Override
	public AnswerAttachedFile toEscapedModel() {
		if (_escapedModelProxy == null) {
			_escapedModelProxy = (AnswerAttachedFile)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelProxyInterfaces,
					new AutoEscapeBeanHandler(this));
		}

		return _escapedModelProxy;
	}

	@Override
	public Object clone() {
		AnswerAttachedFileImpl answerAttachedFileImpl = new AnswerAttachedFileImpl();

		answerAttachedFileImpl.setAnswer_attached_id(getAnswer_attached_id());
		answerAttachedFileImpl.setAnswer_id(getAnswer_id());
		answerAttachedFileImpl.setAttached_file_id(getAttached_file_id());
		answerAttachedFileImpl.setCreated_date(getCreated_date());
		answerAttachedFileImpl.setModified_date(getModified_date());
		answerAttachedFileImpl.setDeleted(getDeleted());

		answerAttachedFileImpl.resetOriginalValues();

		return answerAttachedFileImpl;
	}

	public int compareTo(AnswerAttachedFile answerAttachedFile) {
		String primaryKey = answerAttachedFile.getPrimaryKey();

		return getPrimaryKey().compareTo(primaryKey);
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		AnswerAttachedFile answerAttachedFile = null;

		try {
			answerAttachedFile = (AnswerAttachedFile)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		String primaryKey = answerAttachedFile.getPrimaryKey();

		if (getPrimaryKey().equals(primaryKey)) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey().hashCode();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<AnswerAttachedFile> toCacheModel() {
		AnswerAttachedFileCacheModel answerAttachedFileCacheModel = new AnswerAttachedFileCacheModel();

		answerAttachedFileCacheModel.answer_attached_id = getAnswer_attached_id();

		String answer_attached_id = answerAttachedFileCacheModel.answer_attached_id;

		if ((answer_attached_id != null) && (answer_attached_id.length() == 0)) {
			answerAttachedFileCacheModel.answer_attached_id = null;
		}

		answerAttachedFileCacheModel.answer_id = getAnswer_id();

		String answer_id = answerAttachedFileCacheModel.answer_id;

		if ((answer_id != null) && (answer_id.length() == 0)) {
			answerAttachedFileCacheModel.answer_id = null;
		}

		answerAttachedFileCacheModel.attached_file_id = getAttached_file_id();

		String attached_file_id = answerAttachedFileCacheModel.attached_file_id;

		if ((attached_file_id != null) && (attached_file_id.length() == 0)) {
			answerAttachedFileCacheModel.attached_file_id = null;
		}

		Date created_date = getCreated_date();

		if (created_date != null) {
			answerAttachedFileCacheModel.created_date = created_date.getTime();
		}
		else {
			answerAttachedFileCacheModel.created_date = Long.MIN_VALUE;
		}

		Date modified_date = getModified_date();

		if (modified_date != null) {
			answerAttachedFileCacheModel.modified_date = modified_date.getTime();
		}
		else {
			answerAttachedFileCacheModel.modified_date = Long.MIN_VALUE;
		}

		answerAttachedFileCacheModel.deleted = getDeleted();

		return answerAttachedFileCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(13);

		sb.append("{answer_attached_id=");
		sb.append(getAnswer_attached_id());
		sb.append(", answer_id=");
		sb.append(getAnswer_id());
		sb.append(", attached_file_id=");
		sb.append(getAttached_file_id());
		sb.append(", created_date=");
		sb.append(getCreated_date());
		sb.append(", modified_date=");
		sb.append(getModified_date());
		sb.append(", deleted=");
		sb.append(getDeleted());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(22);

		sb.append("<model><model-name>");
		sb.append("com.fsoft.bn.model.AnswerAttachedFile");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>answer_attached_id</column-name><column-value><![CDATA[");
		sb.append(getAnswer_attached_id());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>answer_id</column-name><column-value><![CDATA[");
		sb.append(getAnswer_id());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>attached_file_id</column-name><column-value><![CDATA[");
		sb.append(getAttached_file_id());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>created_date</column-name><column-value><![CDATA[");
		sb.append(getCreated_date());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modified_date</column-name><column-value><![CDATA[");
		sb.append(getModified_date());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>deleted</column-name><column-value><![CDATA[");
		sb.append(getDeleted());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = AnswerAttachedFile.class.getClassLoader();
	private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
			AnswerAttachedFile.class
		};
	private String _answer_attached_id;
	private String _answer_id;
	private String _attached_file_id;
	private Date _created_date;
	private Date _modified_date;
	private boolean _deleted;
	private AnswerAttachedFile _escapedModelProxy;
}