/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.fsoft.bn.model.impl;

import com.fsoft.bn.model.UserfulContactPhone;
import com.fsoft.bn.model.UserfulContactPhoneModel;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the UserfulContactPhone service. Represents a row in the &quot;BN_UserfulContactPhone&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.fsoft.bn.model.UserfulContactPhoneModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link UserfulContactPhoneImpl}.
 * </p>
 *
 * @author FSOFT
 * @see UserfulContactPhoneImpl
 * @see com.fsoft.bn.model.UserfulContactPhone
 * @see com.fsoft.bn.model.UserfulContactPhoneModel
 * @generated
 */
public class UserfulContactPhoneModelImpl extends BaseModelImpl<UserfulContactPhone>
	implements UserfulContactPhoneModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a userful contact phone model instance should use the {@link com.fsoft.bn.model.UserfulContactPhone} interface instead.
	 */
	public static final String TABLE_NAME = "BN_UserfulContactPhone";
	public static final Object[][] TABLE_COLUMNS = {
			{ "userful_contact_phone_id", Types.VARCHAR },
			{ "userful_contact_name", Types.VARCHAR },
			{ "userful_contact_phone", Types.VARCHAR },
			{ "userful_contact_email", Types.VARCHAR },
			{ "userful_contact_position", Types.VARCHAR },
			{ "userful_contact_address", Types.VARCHAR },
			{ "created_date", Types.TIMESTAMP },
			{ "modified_date", Types.TIMESTAMP },
			{ "deleted", Types.BOOLEAN }
		};
	public static final String TABLE_SQL_CREATE = "create table BN_UserfulContactPhone (userful_contact_phone_id VARCHAR(75) not null primary key,userful_contact_name VARCHAR(75) null,userful_contact_phone VARCHAR(75) null,userful_contact_email VARCHAR(75) null,userful_contact_position VARCHAR(75) null,userful_contact_address VARCHAR(75) null,created_date DATE null,modified_date DATE null,deleted BOOLEAN)";
	public static final String TABLE_SQL_DROP = "drop table BN_UserfulContactPhone";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.fsoft.bn.model.UserfulContactPhone"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.fsoft.bn.model.UserfulContactPhone"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.fsoft.bn.model.UserfulContactPhone"));

	public UserfulContactPhoneModelImpl() {
	}

	public String getPrimaryKey() {
		return _userful_contact_phone_id;
	}

	public void setPrimaryKey(String primaryKey) {
		setUserful_contact_phone_id(primaryKey);
	}

	public Serializable getPrimaryKeyObj() {
		return _userful_contact_phone_id;
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey((String)primaryKeyObj);
	}

	public Class<?> getModelClass() {
		return UserfulContactPhone.class;
	}

	public String getModelClassName() {
		return UserfulContactPhone.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("userful_contact_phone_id", getUserful_contact_phone_id());
		attributes.put("userful_contact_name", getUserful_contact_name());
		attributes.put("userful_contact_phone", getUserful_contact_phone());
		attributes.put("userful_contact_email", getUserful_contact_email());
		attributes.put("userful_contact_position", getUserful_contact_position());
		attributes.put("userful_contact_address", getUserful_contact_address());
		attributes.put("created_date", getCreated_date());
		attributes.put("modified_date", getModified_date());
		attributes.put("deleted", getDeleted());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		String userful_contact_phone_id = (String)attributes.get(
				"userful_contact_phone_id");

		if (userful_contact_phone_id != null) {
			setUserful_contact_phone_id(userful_contact_phone_id);
		}

		String userful_contact_name = (String)attributes.get(
				"userful_contact_name");

		if (userful_contact_name != null) {
			setUserful_contact_name(userful_contact_name);
		}

		String userful_contact_phone = (String)attributes.get(
				"userful_contact_phone");

		if (userful_contact_phone != null) {
			setUserful_contact_phone(userful_contact_phone);
		}

		String userful_contact_email = (String)attributes.get(
				"userful_contact_email");

		if (userful_contact_email != null) {
			setUserful_contact_email(userful_contact_email);
		}

		String userful_contact_position = (String)attributes.get(
				"userful_contact_position");

		if (userful_contact_position != null) {
			setUserful_contact_position(userful_contact_position);
		}

		String userful_contact_address = (String)attributes.get(
				"userful_contact_address");

		if (userful_contact_address != null) {
			setUserful_contact_address(userful_contact_address);
		}

		Date created_date = (Date)attributes.get("created_date");

		if (created_date != null) {
			setCreated_date(created_date);
		}

		Date modified_date = (Date)attributes.get("modified_date");

		if (modified_date != null) {
			setModified_date(modified_date);
		}

		Boolean deleted = (Boolean)attributes.get("deleted");

		if (deleted != null) {
			setDeleted(deleted);
		}
	}

	public String getUserful_contact_phone_id() {
		if (_userful_contact_phone_id == null) {
			return StringPool.BLANK;
		}
		else {
			return _userful_contact_phone_id;
		}
	}

	public void setUserful_contact_phone_id(String userful_contact_phone_id) {
		_userful_contact_phone_id = userful_contact_phone_id;
	}

	public String getUserful_contact_name() {
		if (_userful_contact_name == null) {
			return StringPool.BLANK;
		}
		else {
			return _userful_contact_name;
		}
	}

	public void setUserful_contact_name(String userful_contact_name) {
		_userful_contact_name = userful_contact_name;
	}

	public String getUserful_contact_phone() {
		if (_userful_contact_phone == null) {
			return StringPool.BLANK;
		}
		else {
			return _userful_contact_phone;
		}
	}

	public void setUserful_contact_phone(String userful_contact_phone) {
		_userful_contact_phone = userful_contact_phone;
	}

	public String getUserful_contact_email() {
		if (_userful_contact_email == null) {
			return StringPool.BLANK;
		}
		else {
			return _userful_contact_email;
		}
	}

	public void setUserful_contact_email(String userful_contact_email) {
		_userful_contact_email = userful_contact_email;
	}

	public String getUserful_contact_position() {
		if (_userful_contact_position == null) {
			return StringPool.BLANK;
		}
		else {
			return _userful_contact_position;
		}
	}

	public void setUserful_contact_position(String userful_contact_position) {
		_userful_contact_position = userful_contact_position;
	}

	public String getUserful_contact_address() {
		if (_userful_contact_address == null) {
			return StringPool.BLANK;
		}
		else {
			return _userful_contact_address;
		}
	}

	public void setUserful_contact_address(String userful_contact_address) {
		_userful_contact_address = userful_contact_address;
	}

	public Date getCreated_date() {
		return _created_date;
	}

	public void setCreated_date(Date created_date) {
		_created_date = created_date;
	}

	public Date getModified_date() {
		return _modified_date;
	}

	public void setModified_date(Date modified_date) {
		_modified_date = modified_date;
	}

	public boolean getDeleted() {
		return _deleted;
	}

	public boolean isDeleted() {
		return _deleted;
	}

	public void setDeleted(boolean deleted) {
		_deleted = deleted;
	}

	@Override
	public UserfulContactPhone toEscapedModel() {
		if (_escapedModelProxy == null) {
			_escapedModelProxy = (UserfulContactPhone)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelProxyInterfaces,
					new AutoEscapeBeanHandler(this));
		}

		return _escapedModelProxy;
	}

	@Override
	public Object clone() {
		UserfulContactPhoneImpl userfulContactPhoneImpl = new UserfulContactPhoneImpl();

		userfulContactPhoneImpl.setUserful_contact_phone_id(getUserful_contact_phone_id());
		userfulContactPhoneImpl.setUserful_contact_name(getUserful_contact_name());
		userfulContactPhoneImpl.setUserful_contact_phone(getUserful_contact_phone());
		userfulContactPhoneImpl.setUserful_contact_email(getUserful_contact_email());
		userfulContactPhoneImpl.setUserful_contact_position(getUserful_contact_position());
		userfulContactPhoneImpl.setUserful_contact_address(getUserful_contact_address());
		userfulContactPhoneImpl.setCreated_date(getCreated_date());
		userfulContactPhoneImpl.setModified_date(getModified_date());
		userfulContactPhoneImpl.setDeleted(getDeleted());

		userfulContactPhoneImpl.resetOriginalValues();

		return userfulContactPhoneImpl;
	}

	public int compareTo(UserfulContactPhone userfulContactPhone) {
		String primaryKey = userfulContactPhone.getPrimaryKey();

		return getPrimaryKey().compareTo(primaryKey);
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		UserfulContactPhone userfulContactPhone = null;

		try {
			userfulContactPhone = (UserfulContactPhone)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		String primaryKey = userfulContactPhone.getPrimaryKey();

		if (getPrimaryKey().equals(primaryKey)) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey().hashCode();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<UserfulContactPhone> toCacheModel() {
		UserfulContactPhoneCacheModel userfulContactPhoneCacheModel = new UserfulContactPhoneCacheModel();

		userfulContactPhoneCacheModel.userful_contact_phone_id = getUserful_contact_phone_id();

		String userful_contact_phone_id = userfulContactPhoneCacheModel.userful_contact_phone_id;

		if ((userful_contact_phone_id != null) &&
				(userful_contact_phone_id.length() == 0)) {
			userfulContactPhoneCacheModel.userful_contact_phone_id = null;
		}

		userfulContactPhoneCacheModel.userful_contact_name = getUserful_contact_name();

		String userful_contact_name = userfulContactPhoneCacheModel.userful_contact_name;

		if ((userful_contact_name != null) &&
				(userful_contact_name.length() == 0)) {
			userfulContactPhoneCacheModel.userful_contact_name = null;
		}

		userfulContactPhoneCacheModel.userful_contact_phone = getUserful_contact_phone();

		String userful_contact_phone = userfulContactPhoneCacheModel.userful_contact_phone;

		if ((userful_contact_phone != null) &&
				(userful_contact_phone.length() == 0)) {
			userfulContactPhoneCacheModel.userful_contact_phone = null;
		}

		userfulContactPhoneCacheModel.userful_contact_email = getUserful_contact_email();

		String userful_contact_email = userfulContactPhoneCacheModel.userful_contact_email;

		if ((userful_contact_email != null) &&
				(userful_contact_email.length() == 0)) {
			userfulContactPhoneCacheModel.userful_contact_email = null;
		}

		userfulContactPhoneCacheModel.userful_contact_position = getUserful_contact_position();

		String userful_contact_position = userfulContactPhoneCacheModel.userful_contact_position;

		if ((userful_contact_position != null) &&
				(userful_contact_position.length() == 0)) {
			userfulContactPhoneCacheModel.userful_contact_position = null;
		}

		userfulContactPhoneCacheModel.userful_contact_address = getUserful_contact_address();

		String userful_contact_address = userfulContactPhoneCacheModel.userful_contact_address;

		if ((userful_contact_address != null) &&
				(userful_contact_address.length() == 0)) {
			userfulContactPhoneCacheModel.userful_contact_address = null;
		}

		Date created_date = getCreated_date();

		if (created_date != null) {
			userfulContactPhoneCacheModel.created_date = created_date.getTime();
		}
		else {
			userfulContactPhoneCacheModel.created_date = Long.MIN_VALUE;
		}

		Date modified_date = getModified_date();

		if (modified_date != null) {
			userfulContactPhoneCacheModel.modified_date = modified_date.getTime();
		}
		else {
			userfulContactPhoneCacheModel.modified_date = Long.MIN_VALUE;
		}

		userfulContactPhoneCacheModel.deleted = getDeleted();

		return userfulContactPhoneCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(19);

		sb.append("{userful_contact_phone_id=");
		sb.append(getUserful_contact_phone_id());
		sb.append(", userful_contact_name=");
		sb.append(getUserful_contact_name());
		sb.append(", userful_contact_phone=");
		sb.append(getUserful_contact_phone());
		sb.append(", userful_contact_email=");
		sb.append(getUserful_contact_email());
		sb.append(", userful_contact_position=");
		sb.append(getUserful_contact_position());
		sb.append(", userful_contact_address=");
		sb.append(getUserful_contact_address());
		sb.append(", created_date=");
		sb.append(getCreated_date());
		sb.append(", modified_date=");
		sb.append(getModified_date());
		sb.append(", deleted=");
		sb.append(getDeleted());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(31);

		sb.append("<model><model-name>");
		sb.append("com.fsoft.bn.model.UserfulContactPhone");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>userful_contact_phone_id</column-name><column-value><![CDATA[");
		sb.append(getUserful_contact_phone_id());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userful_contact_name</column-name><column-value><![CDATA[");
		sb.append(getUserful_contact_name());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userful_contact_phone</column-name><column-value><![CDATA[");
		sb.append(getUserful_contact_phone());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userful_contact_email</column-name><column-value><![CDATA[");
		sb.append(getUserful_contact_email());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userful_contact_position</column-name><column-value><![CDATA[");
		sb.append(getUserful_contact_position());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userful_contact_address</column-name><column-value><![CDATA[");
		sb.append(getUserful_contact_address());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>created_date</column-name><column-value><![CDATA[");
		sb.append(getCreated_date());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modified_date</column-name><column-value><![CDATA[");
		sb.append(getModified_date());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>deleted</column-name><column-value><![CDATA[");
		sb.append(getDeleted());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = UserfulContactPhone.class.getClassLoader();
	private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
			UserfulContactPhone.class
		};
	private String _userful_contact_phone_id;
	private String _userful_contact_name;
	private String _userful_contact_phone;
	private String _userful_contact_email;
	private String _userful_contact_position;
	private String _userful_contact_address;
	private Date _created_date;
	private Date _modified_date;
	private boolean _deleted;
	private UserfulContactPhone _escapedModelProxy;
}