/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.fsoft.bn.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the UserSchedule service. Represents a row in the &quot;BN_UserSchedule&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.fsoft.bn.model.impl.UserScheduleModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.fsoft.bn.model.impl.UserScheduleImpl}.
 * </p>
 *
 * @author FSOFT
 * @see UserSchedule
 * @see com.fsoft.bn.model.impl.UserScheduleImpl
 * @see com.fsoft.bn.model.impl.UserScheduleModelImpl
 * @generated
 */
public interface UserScheduleModel extends BaseModel<UserSchedule> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a user schedule model instance should use the {@link UserSchedule} interface instead.
	 */

	/**
	 * Returns the primary key of this user schedule.
	 *
	 * @return the primary key of this user schedule
	 */
	public String getPrimaryKey();

	/**
	 * Sets the primary key of this user schedule.
	 *
	 * @param primaryKey the primary key of this user schedule
	 */
	public void setPrimaryKey(String primaryKey);

	/**
	 * Returns the user_schedule_id of this user schedule.
	 *
	 * @return the user_schedule_id of this user schedule
	 */
	@AutoEscape
	public String getUser_schedule_id();

	/**
	 * Sets the user_schedule_id of this user schedule.
	 *
	 * @param user_schedule_id the user_schedule_id of this user schedule
	 */
	public void setUser_schedule_id(String user_schedule_id);

	/**
	 * Returns the user_id of this user schedule.
	 *
	 * @return the user_id of this user schedule
	 */
	@AutoEscape
	public String getUser_id();

	/**
	 * Sets the user_id of this user schedule.
	 *
	 * @param user_id the user_id of this user schedule
	 */
	public void setUser_id(String user_id);

	/**
	 * Returns the created_date of this user schedule.
	 *
	 * @return the created_date of this user schedule
	 */
	public Date getCreated_date();

	/**
	 * Sets the created_date of this user schedule.
	 *
	 * @param created_date the created_date of this user schedule
	 */
	public void setCreated_date(Date created_date);

	/**
	 * Returns the modified_date of this user schedule.
	 *
	 * @return the modified_date of this user schedule
	 */
	public Date getModified_date();

	/**
	 * Sets the modified_date of this user schedule.
	 *
	 * @param modified_date the modified_date of this user schedule
	 */
	public void setModified_date(Date modified_date);

	/**
	 * Returns the deleted of this user schedule.
	 *
	 * @return the deleted of this user schedule
	 */
	public boolean getDeleted();

	/**
	 * Returns <code>true</code> if this user schedule is deleted.
	 *
	 * @return <code>true</code> if this user schedule is deleted; <code>false</code> otherwise
	 */
	public boolean isDeleted();

	/**
	 * Sets whether this user schedule is deleted.
	 *
	 * @param deleted the deleted of this user schedule
	 */
	public void setDeleted(boolean deleted);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(UserSchedule userSchedule);

	public int hashCode();

	public CacheModel<UserSchedule> toCacheModel();

	public UserSchedule toEscapedModel();

	public String toString();

	public String toXmlString();
}