/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.fsoft.bn.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the UserfulContactPhone service. Represents a row in the &quot;BN_UserfulContactPhone&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.fsoft.bn.model.impl.UserfulContactPhoneModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.fsoft.bn.model.impl.UserfulContactPhoneImpl}.
 * </p>
 *
 * @author FSOFT
 * @see UserfulContactPhone
 * @see com.fsoft.bn.model.impl.UserfulContactPhoneImpl
 * @see com.fsoft.bn.model.impl.UserfulContactPhoneModelImpl
 * @generated
 */
public interface UserfulContactPhoneModel extends BaseModel<UserfulContactPhone> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a userful contact phone model instance should use the {@link UserfulContactPhone} interface instead.
	 */

	/**
	 * Returns the primary key of this userful contact phone.
	 *
	 * @return the primary key of this userful contact phone
	 */
	public String getPrimaryKey();

	/**
	 * Sets the primary key of this userful contact phone.
	 *
	 * @param primaryKey the primary key of this userful contact phone
	 */
	public void setPrimaryKey(String primaryKey);

	/**
	 * Returns the userful_contact_phone_id of this userful contact phone.
	 *
	 * @return the userful_contact_phone_id of this userful contact phone
	 */
	@AutoEscape
	public String getUserful_contact_phone_id();

	/**
	 * Sets the userful_contact_phone_id of this userful contact phone.
	 *
	 * @param userful_contact_phone_id the userful_contact_phone_id of this userful contact phone
	 */
	public void setUserful_contact_phone_id(String userful_contact_phone_id);

	/**
	 * Returns the userful_contact_name of this userful contact phone.
	 *
	 * @return the userful_contact_name of this userful contact phone
	 */
	@AutoEscape
	public String getUserful_contact_name();

	/**
	 * Sets the userful_contact_name of this userful contact phone.
	 *
	 * @param userful_contact_name the userful_contact_name of this userful contact phone
	 */
	public void setUserful_contact_name(String userful_contact_name);

	/**
	 * Returns the userful_contact_phone of this userful contact phone.
	 *
	 * @return the userful_contact_phone of this userful contact phone
	 */
	@AutoEscape
	public String getUserful_contact_phone();

	/**
	 * Sets the userful_contact_phone of this userful contact phone.
	 *
	 * @param userful_contact_phone the userful_contact_phone of this userful contact phone
	 */
	public void setUserful_contact_phone(String userful_contact_phone);

	/**
	 * Returns the userful_contact_email of this userful contact phone.
	 *
	 * @return the userful_contact_email of this userful contact phone
	 */
	@AutoEscape
	public String getUserful_contact_email();

	/**
	 * Sets the userful_contact_email of this userful contact phone.
	 *
	 * @param userful_contact_email the userful_contact_email of this userful contact phone
	 */
	public void setUserful_contact_email(String userful_contact_email);

	/**
	 * Returns the userful_contact_position of this userful contact phone.
	 *
	 * @return the userful_contact_position of this userful contact phone
	 */
	@AutoEscape
	public String getUserful_contact_position();

	/**
	 * Sets the userful_contact_position of this userful contact phone.
	 *
	 * @param userful_contact_position the userful_contact_position of this userful contact phone
	 */
	public void setUserful_contact_position(String userful_contact_position);

	/**
	 * Returns the userful_contact_address of this userful contact phone.
	 *
	 * @return the userful_contact_address of this userful contact phone
	 */
	@AutoEscape
	public String getUserful_contact_address();

	/**
	 * Sets the userful_contact_address of this userful contact phone.
	 *
	 * @param userful_contact_address the userful_contact_address of this userful contact phone
	 */
	public void setUserful_contact_address(String userful_contact_address);

	/**
	 * Returns the created_date of this userful contact phone.
	 *
	 * @return the created_date of this userful contact phone
	 */
	public Date getCreated_date();

	/**
	 * Sets the created_date of this userful contact phone.
	 *
	 * @param created_date the created_date of this userful contact phone
	 */
	public void setCreated_date(Date created_date);

	/**
	 * Returns the modified_date of this userful contact phone.
	 *
	 * @return the modified_date of this userful contact phone
	 */
	public Date getModified_date();

	/**
	 * Sets the modified_date of this userful contact phone.
	 *
	 * @param modified_date the modified_date of this userful contact phone
	 */
	public void setModified_date(Date modified_date);

	/**
	 * Returns the deleted of this userful contact phone.
	 *
	 * @return the deleted of this userful contact phone
	 */
	public boolean getDeleted();

	/**
	 * Returns <code>true</code> if this userful contact phone is deleted.
	 *
	 * @return <code>true</code> if this userful contact phone is deleted; <code>false</code> otherwise
	 */
	public boolean isDeleted();

	/**
	 * Sets whether this userful contact phone is deleted.
	 *
	 * @param deleted the deleted of this userful contact phone
	 */
	public void setDeleted(boolean deleted);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(UserfulContactPhone userfulContactPhone);

	public int hashCode();

	public CacheModel<UserfulContactPhone> toCacheModel();

	public UserfulContactPhone toEscapedModel();

	public String toString();

	public String toXmlString();
}