/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.fsoft.bn.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the BNContact service. Represents a row in the &quot;BN_BNContact&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.fsoft.bn.model.impl.BNContactModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.fsoft.bn.model.impl.BNContactImpl}.
 * </p>
 *
 * @author FSOFT
 * @see BNContact
 * @see com.fsoft.bn.model.impl.BNContactImpl
 * @see com.fsoft.bn.model.impl.BNContactModelImpl
 * @generated
 */
public interface BNContactModel extends BaseModel<BNContact> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a b n contact model instance should use the {@link BNContact} interface instead.
	 */

	/**
	 * Returns the primary key of this b n contact.
	 *
	 * @return the primary key of this b n contact
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this b n contact.
	 *
	 * @param primaryKey the primary key of this b n contact
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the contact ID of this b n contact.
	 *
	 * @return the contact ID of this b n contact
	 */
	public long getContactId();

	/**
	 * Sets the contact ID of this b n contact.
	 *
	 * @param contactId the contact ID of this b n contact
	 */
	public void setContactId(long contactId);

	/**
	 * Returns the department key of this b n contact.
	 *
	 * @return the department key of this b n contact
	 */
	@AutoEscape
	public String getDepartmentKey();

	/**
	 * Sets the department key of this b n contact.
	 *
	 * @param departmentKey the department key of this b n contact
	 */
	public void setDepartmentKey(String departmentKey);

	/**
	 * Returns the name of this b n contact.
	 *
	 * @return the name of this b n contact
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this b n contact.
	 *
	 * @param name the name of this b n contact
	 */
	public void setName(String name);

	/**
	 * Returns the regency of this b n contact.
	 *
	 * @return the regency of this b n contact
	 */
	@AutoEscape
	public String getRegency();

	/**
	 * Sets the regency of this b n contact.
	 *
	 * @param regency the regency of this b n contact
	 */
	public void setRegency(String regency);

	/**
	 * Returns the phone number of this b n contact.
	 *
	 * @return the phone number of this b n contact
	 */
	@AutoEscape
	public String getPhoneNumber();

	/**
	 * Sets the phone number of this b n contact.
	 *
	 * @param phoneNumber the phone number of this b n contact
	 */
	public void setPhoneNumber(String phoneNumber);

	/**
	 * Returns the email of this b n contact.
	 *
	 * @return the email of this b n contact
	 */
	@AutoEscape
	public String getEmail();

	/**
	 * Sets the email of this b n contact.
	 *
	 * @param email the email of this b n contact
	 */
	public void setEmail(String email);

	/**
	 * Returns the created date of this b n contact.
	 *
	 * @return the created date of this b n contact
	 */
	public Date getCreatedDate();

	/**
	 * Sets the created date of this b n contact.
	 *
	 * @param createdDate the created date of this b n contact
	 */
	public void setCreatedDate(Date createdDate);

	/**
	 * Returns the modified date of this b n contact.
	 *
	 * @return the modified date of this b n contact
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this b n contact.
	 *
	 * @param modifiedDate the modified date of this b n contact
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the deleted of this b n contact.
	 *
	 * @return the deleted of this b n contact
	 */
	public boolean getDeleted();

	/**
	 * Returns <code>true</code> if this b n contact is deleted.
	 *
	 * @return <code>true</code> if this b n contact is deleted; <code>false</code> otherwise
	 */
	public boolean isDeleted();

	/**
	 * Sets whether this b n contact is deleted.
	 *
	 * @param deleted the deleted of this b n contact
	 */
	public void setDeleted(boolean deleted);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(BNContact bnContact);

	public int hashCode();

	public CacheModel<BNContact> toCacheModel();

	public BNContact toEscapedModel();

	public String toString();

	public String toXmlString();
}