/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.fsoft.bn.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Enrolment service. Represents a row in the &quot;BN_Enrolment&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.fsoft.bn.model.impl.EnrolmentModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.fsoft.bn.model.impl.EnrolmentImpl}.
 * </p>
 *
 * @author FSOFT
 * @see Enrolment
 * @see com.fsoft.bn.model.impl.EnrolmentImpl
 * @see com.fsoft.bn.model.impl.EnrolmentModelImpl
 * @generated
 */
public interface EnrolmentModel extends BaseModel<Enrolment> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a enrolment model instance should use the {@link Enrolment} interface instead.
	 */

	/**
	 * Returns the primary key of this enrolment.
	 *
	 * @return the primary key of this enrolment
	 */
	public String getPrimaryKey();

	/**
	 * Sets the primary key of this enrolment.
	 *
	 * @param primaryKey the primary key of this enrolment
	 */
	public void setPrimaryKey(String primaryKey);

	/**
	 * Returns the enrolment_id of this enrolment.
	 *
	 * @return the enrolment_id of this enrolment
	 */
	@AutoEscape
	public String getEnrolment_id();

	/**
	 * Sets the enrolment_id of this enrolment.
	 *
	 * @param enrolment_id the enrolment_id of this enrolment
	 */
	public void setEnrolment_id(String enrolment_id);

	/**
	 * Returns the hs_ten of this enrolment.
	 *
	 * @return the hs_ten of this enrolment
	 */
	@AutoEscape
	public String getHs_ten();

	/**
	 * Sets the hs_ten of this enrolment.
	 *
	 * @param hs_ten the hs_ten of this enrolment
	 */
	public void setHs_ten(String hs_ten);

	/**
	 * Returns the hs_ho of this enrolment.
	 *
	 * @return the hs_ho of this enrolment
	 */
	@AutoEscape
	public String getHs_ho();

	/**
	 * Sets the hs_ho of this enrolment.
	 *
	 * @param hs_ho the hs_ho of this enrolment
	 */
	public void setHs_ho(String hs_ho);

	/**
	 * Returns the hs_quoc_tich of this enrolment.
	 *
	 * @return the hs_quoc_tich of this enrolment
	 */
	@AutoEscape
	public String getHs_quoc_tich();

	/**
	 * Sets the hs_quoc_tich of this enrolment.
	 *
	 * @param hs_quoc_tich the hs_quoc_tich of this enrolment
	 */
	public void setHs_quoc_tich(String hs_quoc_tich);

	/**
	 * Returns the hs_ngay_sinh of this enrolment.
	 *
	 * @return the hs_ngay_sinh of this enrolment
	 */
	public Date getHs_ngay_sinh();

	/**
	 * Sets the hs_ngay_sinh of this enrolment.
	 *
	 * @param hs_ngay_sinh the hs_ngay_sinh of this enrolment
	 */
	public void setHs_ngay_sinh(Date hs_ngay_sinh);

	/**
	 * Returns the hs_so_dien_thoai of this enrolment.
	 *
	 * @return the hs_so_dien_thoai of this enrolment
	 */
	@AutoEscape
	public String getHs_so_dien_thoai();

	/**
	 * Sets the hs_so_dien_thoai of this enrolment.
	 *
	 * @param hs_so_dien_thoai the hs_so_dien_thoai of this enrolment
	 */
	public void setHs_so_dien_thoai(String hs_so_dien_thoai);

	/**
	 * Returns the hs_nguoi_lien_he of this enrolment.
	 *
	 * @return the hs_nguoi_lien_he of this enrolment
	 */
	@AutoEscape
	public String getHs_nguoi_lien_he();

	/**
	 * Sets the hs_nguoi_lien_he of this enrolment.
	 *
	 * @param hs_nguoi_lien_he the hs_nguoi_lien_he of this enrolment
	 */
	public void setHs_nguoi_lien_he(String hs_nguoi_lien_he);

	/**
	 * Returns the hs_quan_he_voi_hoc_sinh of this enrolment.
	 *
	 * @return the hs_quan_he_voi_hoc_sinh of this enrolment
	 */
	@AutoEscape
	public String getHs_quan_he_voi_hoc_sinh();

	/**
	 * Sets the hs_quan_he_voi_hoc_sinh of this enrolment.
	 *
	 * @param hs_quan_he_voi_hoc_sinh the hs_quan_he_voi_hoc_sinh of this enrolment
	 */
	public void setHs_quan_he_voi_hoc_sinh(String hs_quan_he_voi_hoc_sinh);

	/**
	 * Returns the hk_dia_chi of this enrolment.
	 *
	 * @return the hk_dia_chi of this enrolment
	 */
	@AutoEscape
	public String getHk_dia_chi();

	/**
	 * Sets the hk_dia_chi of this enrolment.
	 *
	 * @param hk_dia_chi the hk_dia_chi of this enrolment
	 */
	public void setHk_dia_chi(String hk_dia_chi);

	/**
	 * Returns the hk_thanh_pho of this enrolment.
	 *
	 * @return the hk_thanh_pho of this enrolment
	 */
	@AutoEscape
	public String getHk_thanh_pho();

	/**
	 * Sets the hk_thanh_pho of this enrolment.
	 *
	 * @param hk_thanh_pho the hk_thanh_pho of this enrolment
	 */
	public void setHk_thanh_pho(String hk_thanh_pho);

	/**
	 * Returns the hk_tinh of this enrolment.
	 *
	 * @return the hk_tinh of this enrolment
	 */
	@AutoEscape
	public String getHk_tinh();

	/**
	 * Sets the hk_tinh of this enrolment.
	 *
	 * @param hk_tinh the hk_tinh of this enrolment
	 */
	public void setHk_tinh(String hk_tinh);

	/**
	 * Returns the hk_quoc_gia of this enrolment.
	 *
	 * @return the hk_quoc_gia of this enrolment
	 */
	@AutoEscape
	public String getHk_quoc_gia();

	/**
	 * Sets the hk_quoc_gia of this enrolment.
	 *
	 * @param hk_quoc_gia the hk_quoc_gia of this enrolment
	 */
	public void setHk_quoc_gia(String hk_quoc_gia);

	/**
	 * Returns the cm_ten of this enrolment.
	 *
	 * @return the cm_ten of this enrolment
	 */
	@AutoEscape
	public String getCm_ten();

	/**
	 * Sets the cm_ten of this enrolment.
	 *
	 * @param cm_ten the cm_ten of this enrolment
	 */
	public void setCm_ten(String cm_ten);

	/**
	 * Returns the cm_ho of this enrolment.
	 *
	 * @return the cm_ho of this enrolment
	 */
	@AutoEscape
	public String getCm_ho();

	/**
	 * Sets the cm_ho of this enrolment.
	 *
	 * @param cm_ho the cm_ho of this enrolment
	 */
	public void setCm_ho(String cm_ho);

	/**
	 * Returns the cm_quan_he_voi_hoc_sinh of this enrolment.
	 *
	 * @return the cm_quan_he_voi_hoc_sinh of this enrolment
	 */
	@AutoEscape
	public String getCm_quan_he_voi_hoc_sinh();

	/**
	 * Sets the cm_quan_he_voi_hoc_sinh of this enrolment.
	 *
	 * @param cm_quan_he_voi_hoc_sinh the cm_quan_he_voi_hoc_sinh of this enrolment
	 */
	public void setCm_quan_he_voi_hoc_sinh(String cm_quan_he_voi_hoc_sinh);

	/**
	 * Returns the cm_dia_chi_email of this enrolment.
	 *
	 * @return the cm_dia_chi_email of this enrolment
	 */
	@AutoEscape
	public String getCm_dia_chi_email();

	/**
	 * Sets the cm_dia_chi_email of this enrolment.
	 *
	 * @param cm_dia_chi_email the cm_dia_chi_email of this enrolment
	 */
	public void setCm_dia_chi_email(String cm_dia_chi_email);

	/**
	 * Returns the cm_so_dien_thoai_di_dong of this enrolment.
	 *
	 * @return the cm_so_dien_thoai_di_dong of this enrolment
	 */
	@AutoEscape
	public String getCm_so_dien_thoai_di_dong();

	/**
	 * Sets the cm_so_dien_thoai_di_dong of this enrolment.
	 *
	 * @param cm_so_dien_thoai_di_dong the cm_so_dien_thoai_di_dong of this enrolment
	 */
	public void setCm_so_dien_thoai_di_dong(String cm_so_dien_thoai_di_dong);

	/**
	 * Returns the cm_dien_thoai_noi_lam_viec of this enrolment.
	 *
	 * @return the cm_dien_thoai_noi_lam_viec of this enrolment
	 */
	@AutoEscape
	public String getCm_dien_thoai_noi_lam_viec();

	/**
	 * Sets the cm_dien_thoai_noi_lam_viec of this enrolment.
	 *
	 * @param cm_dien_thoai_noi_lam_viec the cm_dien_thoai_noi_lam_viec of this enrolment
	 */
	public void setCm_dien_thoai_noi_lam_viec(String cm_dien_thoai_noi_lam_viec);

	/**
	 * Returns the cm_ten_cong_ty of this enrolment.
	 *
	 * @return the cm_ten_cong_ty of this enrolment
	 */
	@AutoEscape
	public String getCm_ten_cong_ty();

	/**
	 * Sets the cm_ten_cong_ty of this enrolment.
	 *
	 * @param cm_ten_cong_ty the cm_ten_cong_ty of this enrolment
	 */
	public void setCm_ten_cong_ty(String cm_ten_cong_ty);

	/**
	 * Returns the cm_chuc_danh of this enrolment.
	 *
	 * @return the cm_chuc_danh of this enrolment
	 */
	@AutoEscape
	public String getCm_chuc_danh();

	/**
	 * Sets the cm_chuc_danh of this enrolment.
	 *
	 * @param cm_chuc_danh the cm_chuc_danh of this enrolment
	 */
	public void setCm_chuc_danh(String cm_chuc_danh);

	/**
	 * Returns the k_lop of this enrolment.
	 *
	 * @return the k_lop of this enrolment
	 */
	@AutoEscape
	public String getK_lop();

	/**
	 * Sets the k_lop of this enrolment.
	 *
	 * @param k_lop the k_lop of this enrolment
	 */
	public void setK_lop(String k_lop);

	/**
	 * Returns the k_nam_hoc of this enrolment.
	 *
	 * @return the k_nam_hoc of this enrolment
	 */
	@AutoEscape
	public String getK_nam_hoc();

	/**
	 * Sets the k_nam_hoc of this enrolment.
	 *
	 * @param k_nam_hoc the k_nam_hoc of this enrolment
	 */
	public void setK_nam_hoc(String k_nam_hoc);

	/**
	 * Returns the k_truong_hien_dang_hoc of this enrolment.
	 *
	 * @return the k_truong_hien_dang_hoc of this enrolment
	 */
	@AutoEscape
	public String getK_truong_hien_dang_hoc();

	/**
	 * Sets the k_truong_hien_dang_hoc of this enrolment.
	 *
	 * @param k_truong_hien_dang_hoc the k_truong_hien_dang_hoc of this enrolment
	 */
	public void setK_truong_hien_dang_hoc(String k_truong_hien_dang_hoc);

	/**
	 * Returns the k_sao_ma_biet_den of this enrolment.
	 *
	 * @return the k_sao_ma_biet_den of this enrolment
	 */
	@AutoEscape
	public String getK_sao_ma_biet_den();

	/**
	 * Sets the k_sao_ma_biet_den of this enrolment.
	 *
	 * @param k_sao_ma_biet_den the k_sao_ma_biet_den of this enrolment
	 */
	public void setK_sao_ma_biet_den(String k_sao_ma_biet_den);

	/**
	 * Returns the k_nguoi_gioi_thieu of this enrolment.
	 *
	 * @return the k_nguoi_gioi_thieu of this enrolment
	 */
	@AutoEscape
	public String getK_nguoi_gioi_thieu();

	/**
	 * Sets the k_nguoi_gioi_thieu of this enrolment.
	 *
	 * @param k_nguoi_gioi_thieu the k_nguoi_gioi_thieu of this enrolment
	 */
	public void setK_nguoi_gioi_thieu(String k_nguoi_gioi_thieu);

	/**
	 * Returns the k_thac_mac of this enrolment.
	 *
	 * @return the k_thac_mac of this enrolment
	 */
	@AutoEscape
	public String getK_thac_mac();

	/**
	 * Sets the k_thac_mac of this enrolment.
	 *
	 * @param k_thac_mac the k_thac_mac of this enrolment
	 */
	public void setK_thac_mac(String k_thac_mac);

	/**
	 * Returns the trang_thai of this enrolment.
	 *
	 * @return the trang_thai of this enrolment
	 */
	@AutoEscape
	public String getTrang_thai();

	/**
	 * Sets the trang_thai of this enrolment.
	 *
	 * @param trang_thai the trang_thai of this enrolment
	 */
	public void setTrang_thai(String trang_thai);

	/**
	 * Returns the created_date of this enrolment.
	 *
	 * @return the created_date of this enrolment
	 */
	public Date getCreated_date();

	/**
	 * Sets the created_date of this enrolment.
	 *
	 * @param created_date the created_date of this enrolment
	 */
	public void setCreated_date(Date created_date);

	/**
	 * Returns the modified_date of this enrolment.
	 *
	 * @return the modified_date of this enrolment
	 */
	public Date getModified_date();

	/**
	 * Sets the modified_date of this enrolment.
	 *
	 * @param modified_date the modified_date of this enrolment
	 */
	public void setModified_date(Date modified_date);

	/**
	 * Returns the deleted of this enrolment.
	 *
	 * @return the deleted of this enrolment
	 */
	public boolean getDeleted();

	/**
	 * Returns <code>true</code> if this enrolment is deleted.
	 *
	 * @return <code>true</code> if this enrolment is deleted; <code>false</code> otherwise
	 */
	public boolean isDeleted();

	/**
	 * Sets whether this enrolment is deleted.
	 *
	 * @param deleted the deleted of this enrolment
	 */
	public void setDeleted(boolean deleted);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(Enrolment enrolment);

	public int hashCode();

	public CacheModel<Enrolment> toCacheModel();

	public Enrolment toEscapedModel();

	public String toString();

	public String toXmlString();
}