/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.fsoft.bn.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the PreschoolStudent service. Represents a row in the &quot;BN_PreschoolStudent&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.fsoft.bn.model.impl.PreschoolStudentModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.fsoft.bn.model.impl.PreschoolStudentImpl}.
 * </p>
 *
 * @author FSOFT
 * @see PreschoolStudent
 * @see com.fsoft.bn.model.impl.PreschoolStudentImpl
 * @see com.fsoft.bn.model.impl.PreschoolStudentModelImpl
 * @generated
 */
public interface PreschoolStudentModel extends BaseModel<PreschoolStudent> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a preschool student model instance should use the {@link PreschoolStudent} interface instead.
	 */

	/**
	 * Returns the primary key of this preschool student.
	 *
	 * @return the primary key of this preschool student
	 */
	public String getPrimaryKey();

	/**
	 * Sets the primary key of this preschool student.
	 *
	 * @param primaryKey the primary key of this preschool student
	 */
	public void setPrimaryKey(String primaryKey);

	/**
	 * Returns the student_id of this preschool student.
	 *
	 * @return the student_id of this preschool student
	 */
	@AutoEscape
	public String getStudent_id();

	/**
	 * Sets the student_id of this preschool student.
	 *
	 * @param student_id the student_id of this preschool student
	 */
	public void setStudent_id(String student_id);

	/**
	 * Returns the student_name of this preschool student.
	 *
	 * @return the student_name of this preschool student
	 */
	@AutoEscape
	public String getStudent_name();

	/**
	 * Sets the student_name of this preschool student.
	 *
	 * @param student_name the student_name of this preschool student
	 */
	public void setStudent_name(String student_name);

	/**
	 * Returns the student_sex of this preschool student.
	 *
	 * @return the student_sex of this preschool student
	 */
	@AutoEscape
	public String getStudent_sex();

	/**
	 * Sets the student_sex of this preschool student.
	 *
	 * @param student_sex the student_sex of this preschool student
	 */
	public void setStudent_sex(String student_sex);

	/**
	 * Returns the student_dob of this preschool student.
	 *
	 * @return the student_dob of this preschool student
	 */
	@AutoEscape
	public String getStudent_dob();

	/**
	 * Sets the student_dob of this preschool student.
	 *
	 * @param student_dob the student_dob of this preschool student
	 */
	public void setStudent_dob(String student_dob);

	/**
	 * Returns the student_place of birth of this preschool student.
	 *
	 * @return the student_place of birth of this preschool student
	 */
	@AutoEscape
	public String getStudent_placeOfBirth();

	/**
	 * Sets the student_place of birth of this preschool student.
	 *
	 * @param student_placeOfBirth the student_place of birth of this preschool student
	 */
	public void setStudent_placeOfBirth(String student_placeOfBirth);

	/**
	 * Returns the student_nationality of this preschool student.
	 *
	 * @return the student_nationality of this preschool student
	 */
	@AutoEscape
	public String getStudent_nationality();

	/**
	 * Sets the student_nationality of this preschool student.
	 *
	 * @param student_nationality the student_nationality of this preschool student
	 */
	public void setStudent_nationality(String student_nationality);

	/**
	 * Returns the student_phone number of this preschool student.
	 *
	 * @return the student_phone number of this preschool student
	 */
	@AutoEscape
	public String getStudent_phoneNumber();

	/**
	 * Sets the student_phone number of this preschool student.
	 *
	 * @param student_phoneNumber the student_phone number of this preschool student
	 */
	public void setStudent_phoneNumber(String student_phoneNumber);

	/**
	 * Returns the student_address of this preschool student.
	 *
	 * @return the student_address of this preschool student
	 */
	@AutoEscape
	public String getStudent_address();

	/**
	 * Sets the student_address of this preschool student.
	 *
	 * @param student_address the student_address of this preschool student
	 */
	public void setStudent_address(String student_address);

	/**
	 * Returns the student_heatlh status of this preschool student.
	 *
	 * @return the student_heatlh status of this preschool student
	 */
	@AutoEscape
	public String getStudent_heatlhStatus();

	/**
	 * Sets the student_heatlh status of this preschool student.
	 *
	 * @param student_heatlhStatus the student_heatlh status of this preschool student
	 */
	public void setStudent_heatlhStatus(String student_heatlhStatus);

	/**
	 * Returns the student_height of this preschool student.
	 *
	 * @return the student_height of this preschool student
	 */
	@AutoEscape
	public String getStudent_height();

	/**
	 * Sets the student_height of this preschool student.
	 *
	 * @param student_height the student_height of this preschool student
	 */
	public void setStudent_height(String student_height);

	/**
	 * Returns the student_weight of this preschool student.
	 *
	 * @return the student_weight of this preschool student
	 */
	@AutoEscape
	public String getStudent_weight();

	/**
	 * Sets the student_weight of this preschool student.
	 *
	 * @param student_weight the student_weight of this preschool student
	 */
	public void setStudent_weight(String student_weight);

	/**
	 * Returns the student_contact name of this preschool student.
	 *
	 * @return the student_contact name of this preschool student
	 */
	@AutoEscape
	public String getStudent_contactName();

	/**
	 * Sets the student_contact name of this preschool student.
	 *
	 * @param student_contactName the student_contact name of this preschool student
	 */
	public void setStudent_contactName(String student_contactName);

	/**
	 * Returns the student_contact relationship of this preschool student.
	 *
	 * @return the student_contact relationship of this preschool student
	 */
	@AutoEscape
	public String getStudent_contactRelationship();

	/**
	 * Sets the student_contact relationship of this preschool student.
	 *
	 * @param student_contactRelationship the student_contact relationship of this preschool student
	 */
	public void setStudent_contactRelationship(
		String student_contactRelationship);

	/**
	 * Returns the student_contact phone number of this preschool student.
	 *
	 * @return the student_contact phone number of this preschool student
	 */
	@AutoEscape
	public String getStudent_contactPhoneNumber();

	/**
	 * Sets the student_contact phone number of this preschool student.
	 *
	 * @param student_contactPhoneNumber the student_contact phone number of this preschool student
	 */
	public void setStudent_contactPhoneNumber(String student_contactPhoneNumber);

	/**
	 * Returns the student_contact email of this preschool student.
	 *
	 * @return the student_contact email of this preschool student
	 */
	@AutoEscape
	public String getStudent_contactEmail();

	/**
	 * Sets the student_contact email of this preschool student.
	 *
	 * @param student_contactEmail the student_contact email of this preschool student
	 */
	public void setStudent_contactEmail(String student_contactEmail);

	/**
	 * Returns the student_how to know b m of this preschool student.
	 *
	 * @return the student_how to know b m of this preschool student
	 */
	@AutoEscape
	public String getStudent_howToKnowBM();

	/**
	 * Sets the student_how to know b m of this preschool student.
	 *
	 * @param student_howToKnowBM the student_how to know b m of this preschool student
	 */
	public void setStudent_howToKnowBM(String student_howToKnowBM);

	/**
	 * Returns the student_who introduce of this preschool student.
	 *
	 * @return the student_who introduce of this preschool student
	 */
	@AutoEscape
	public String getStudent_whoIntroduce();

	/**
	 * Sets the student_who introduce of this preschool student.
	 *
	 * @param student_whoIntroduce the student_who introduce of this preschool student
	 */
	public void setStudent_whoIntroduce(String student_whoIntroduce);

	/**
	 * Returns the student_any confuse of this preschool student.
	 *
	 * @return the student_any confuse of this preschool student
	 */
	@AutoEscape
	public String getStudent_anyConfuse();

	/**
	 * Sets the student_any confuse of this preschool student.
	 *
	 * @param student_anyConfuse the student_any confuse of this preschool student
	 */
	public void setStudent_anyConfuse(String student_anyConfuse);

	/**
	 * Returns the status of this preschool student.
	 *
	 * @return the status of this preschool student
	 */
	@AutoEscape
	public String getStatus();

	/**
	 * Sets the status of this preschool student.
	 *
	 * @param status the status of this preschool student
	 */
	public void setStatus(String status);

	/**
	 * Returns the created_date of this preschool student.
	 *
	 * @return the created_date of this preschool student
	 */
	public Date getCreated_date();

	/**
	 * Sets the created_date of this preschool student.
	 *
	 * @param created_date the created_date of this preschool student
	 */
	public void setCreated_date(Date created_date);

	/**
	 * Returns the modified_date of this preschool student.
	 *
	 * @return the modified_date of this preschool student
	 */
	public Date getModified_date();

	/**
	 * Sets the modified_date of this preschool student.
	 *
	 * @param modified_date the modified_date of this preschool student
	 */
	public void setModified_date(Date modified_date);

	/**
	 * Returns the deleted of this preschool student.
	 *
	 * @return the deleted of this preschool student
	 */
	public boolean getDeleted();

	/**
	 * Returns <code>true</code> if this preschool student is deleted.
	 *
	 * @return <code>true</code> if this preschool student is deleted; <code>false</code> otherwise
	 */
	public boolean isDeleted();

	/**
	 * Sets whether this preschool student is deleted.
	 *
	 * @param deleted the deleted of this preschool student
	 */
	public void setDeleted(boolean deleted);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(PreschoolStudent preschoolStudent);

	public int hashCode();

	public CacheModel<PreschoolStudent> toCacheModel();

	public PreschoolStudent toEscapedModel();

	public String toString();

	public String toXmlString();
}