/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.fsoft.bn.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the PrimarySchoolParent service. Represents a row in the &quot;BN_PrimarySchoolParent&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.fsoft.bn.model.impl.PrimarySchoolParentModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.fsoft.bn.model.impl.PrimarySchoolParentImpl}.
 * </p>
 *
 * @author FSOFT
 * @see PrimarySchoolParent
 * @see com.fsoft.bn.model.impl.PrimarySchoolParentImpl
 * @see com.fsoft.bn.model.impl.PrimarySchoolParentModelImpl
 * @generated
 */
public interface PrimarySchoolParentModel extends BaseModel<PrimarySchoolParent> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a primary school parent model instance should use the {@link PrimarySchoolParent} interface instead.
	 */

	/**
	 * Returns the primary key of this primary school parent.
	 *
	 * @return the primary key of this primary school parent
	 */
	public String getPrimaryKey();

	/**
	 * Sets the primary key of this primary school parent.
	 *
	 * @param primaryKey the primary key of this primary school parent
	 */
	public void setPrimaryKey(String primaryKey);

	/**
	 * Returns the primary school parent_id of this primary school parent.
	 *
	 * @return the primary school parent_id of this primary school parent
	 */
	@AutoEscape
	public String getPrimarySchoolParent_id();

	/**
	 * Sets the primary school parent_id of this primary school parent.
	 *
	 * @param primarySchoolParent_id the primary school parent_id of this primary school parent
	 */
	public void setPrimarySchoolParent_id(String primarySchoolParent_id);

	/**
	 * Returns the primary student_id of this primary school parent.
	 *
	 * @return the primary student_id of this primary school parent
	 */
	@AutoEscape
	public String getPrimaryStudent_id();

	/**
	 * Sets the primary student_id of this primary school parent.
	 *
	 * @param primaryStudent_id the primary student_id of this primary school parent
	 */
	public void setPrimaryStudent_id(String primaryStudent_id);

	/**
	 * Returns the name of this primary school parent.
	 *
	 * @return the name of this primary school parent
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this primary school parent.
	 *
	 * @param name the name of this primary school parent
	 */
	public void setName(String name);

	/**
	 * Returns the nationality of this primary school parent.
	 *
	 * @return the nationality of this primary school parent
	 */
	@AutoEscape
	public String getNationality();

	/**
	 * Sets the nationality of this primary school parent.
	 *
	 * @param nationality the nationality of this primary school parent
	 */
	public void setNationality(String nationality);

	/**
	 * Returns the id card number of this primary school parent.
	 *
	 * @return the id card number of this primary school parent
	 */
	@AutoEscape
	public String getIdCardNumber();

	/**
	 * Sets the id card number of this primary school parent.
	 *
	 * @param idCardNumber the id card number of this primary school parent
	 */
	public void setIdCardNumber(String idCardNumber);

	/**
	 * Returns the phone number of this primary school parent.
	 *
	 * @return the phone number of this primary school parent
	 */
	@AutoEscape
	public String getPhoneNumber();

	/**
	 * Sets the phone number of this primary school parent.
	 *
	 * @param phoneNumber the phone number of this primary school parent
	 */
	public void setPhoneNumber(String phoneNumber);

	/**
	 * Returns the email of this primary school parent.
	 *
	 * @return the email of this primary school parent
	 */
	@AutoEscape
	public String getEmail();

	/**
	 * Sets the email of this primary school parent.
	 *
	 * @param Email the email of this primary school parent
	 */
	public void setEmail(String Email);

	/**
	 * Returns the job of this primary school parent.
	 *
	 * @return the job of this primary school parent
	 */
	@AutoEscape
	public String getJob();

	/**
	 * Sets the job of this primary school parent.
	 *
	 * @param job the job of this primary school parent
	 */
	public void setJob(String job);

	/**
	 * Returns the job_position of this primary school parent.
	 *
	 * @return the job_position of this primary school parent
	 */
	@AutoEscape
	public String getJob_position();

	/**
	 * Sets the job_position of this primary school parent.
	 *
	 * @param job_position the job_position of this primary school parent
	 */
	public void setJob_position(String job_position);

	/**
	 * Returns the workplace of this primary school parent.
	 *
	 * @return the workplace of this primary school parent
	 */
	@AutoEscape
	public String getWorkplace();

	/**
	 * Sets the workplace of this primary school parent.
	 *
	 * @param workplace the workplace of this primary school parent
	 */
	public void setWorkplace(String workplace);

	/**
	 * Returns the is mother of this primary school parent.
	 *
	 * @return the is mother of this primary school parent
	 */
	public boolean getIsMother();

	/**
	 * Returns <code>true</code> if this primary school parent is is mother.
	 *
	 * @return <code>true</code> if this primary school parent is is mother; <code>false</code> otherwise
	 */
	public boolean isIsMother();

	/**
	 * Sets whether this primary school parent is is mother.
	 *
	 * @param isMother the is mother of this primary school parent
	 */
	public void setIsMother(boolean isMother);

	/**
	 * Returns the created_date of this primary school parent.
	 *
	 * @return the created_date of this primary school parent
	 */
	public Date getCreated_date();

	/**
	 * Sets the created_date of this primary school parent.
	 *
	 * @param created_date the created_date of this primary school parent
	 */
	public void setCreated_date(Date created_date);

	/**
	 * Returns the modified_date of this primary school parent.
	 *
	 * @return the modified_date of this primary school parent
	 */
	public Date getModified_date();

	/**
	 * Sets the modified_date of this primary school parent.
	 *
	 * @param modified_date the modified_date of this primary school parent
	 */
	public void setModified_date(Date modified_date);

	/**
	 * Returns the deleted of this primary school parent.
	 *
	 * @return the deleted of this primary school parent
	 */
	public boolean getDeleted();

	/**
	 * Returns <code>true</code> if this primary school parent is deleted.
	 *
	 * @return <code>true</code> if this primary school parent is deleted; <code>false</code> otherwise
	 */
	public boolean isDeleted();

	/**
	 * Sets whether this primary school parent is deleted.
	 *
	 * @param deleted the deleted of this primary school parent
	 */
	public void setDeleted(boolean deleted);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(PrimarySchoolParent primarySchoolParent);

	public int hashCode();

	public CacheModel<PrimarySchoolParent> toCacheModel();

	public PrimarySchoolParent toEscapedModel();

	public String toString();

	public String toXmlString();
}