/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.fsoft.bn.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the PrimarySchoolStudent service. Represents a row in the &quot;BN_PrimarySchoolStudent&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.fsoft.bn.model.impl.PrimarySchoolStudentModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.fsoft.bn.model.impl.PrimarySchoolStudentImpl}.
 * </p>
 *
 * @author FSOFT
 * @see PrimarySchoolStudent
 * @see com.fsoft.bn.model.impl.PrimarySchoolStudentImpl
 * @see com.fsoft.bn.model.impl.PrimarySchoolStudentModelImpl
 * @generated
 */
public interface PrimarySchoolStudentModel extends BaseModel<PrimarySchoolStudent> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a primary school student model instance should use the {@link PrimarySchoolStudent} interface instead.
	 */

	/**
	 * Returns the primary key of this primary school student.
	 *
	 * @return the primary key of this primary school student
	 */
	public String getPrimaryKey();

	/**
	 * Sets the primary key of this primary school student.
	 *
	 * @param primaryKey the primary key of this primary school student
	 */
	public void setPrimaryKey(String primaryKey);

	/**
	 * Returns the primary student_id of this primary school student.
	 *
	 * @return the primary student_id of this primary school student
	 */
	@AutoEscape
	public String getPrimaryStudent_id();

	/**
	 * Sets the primary student_id of this primary school student.
	 *
	 * @param primaryStudent_id the primary student_id of this primary school student
	 */
	public void setPrimaryStudent_id(String primaryStudent_id);

	/**
	 * Returns the student_name of this primary school student.
	 *
	 * @return the student_name of this primary school student
	 */
	@AutoEscape
	public String getStudent_name();

	/**
	 * Sets the student_name of this primary school student.
	 *
	 * @param student_name the student_name of this primary school student
	 */
	public void setStudent_name(String student_name);

	/**
	 * Returns the student_sex of this primary school student.
	 *
	 * @return the student_sex of this primary school student
	 */
	@AutoEscape
	public String getStudent_sex();

	/**
	 * Sets the student_sex of this primary school student.
	 *
	 * @param student_sex the student_sex of this primary school student
	 */
	public void setStudent_sex(String student_sex);

	/**
	 * Returns the student_dob of this primary school student.
	 *
	 * @return the student_dob of this primary school student
	 */
	@AutoEscape
	public String getStudent_dob();

	/**
	 * Sets the student_dob of this primary school student.
	 *
	 * @param student_dob the student_dob of this primary school student
	 */
	public void setStudent_dob(String student_dob);

	/**
	 * Returns the student_place of birth of this primary school student.
	 *
	 * @return the student_place of birth of this primary school student
	 */
	@AutoEscape
	public String getStudent_placeOfBirth();

	/**
	 * Sets the student_place of birth of this primary school student.
	 *
	 * @param student_placeOfBirth the student_place of birth of this primary school student
	 */
	public void setStudent_placeOfBirth(String student_placeOfBirth);

	/**
	 * Returns the student_nationality of this primary school student.
	 *
	 * @return the student_nationality of this primary school student
	 */
	@AutoEscape
	public String getStudent_nationality();

	/**
	 * Sets the student_nationality of this primary school student.
	 *
	 * @param student_nationality the student_nationality of this primary school student
	 */
	public void setStudent_nationality(String student_nationality);

	/**
	 * Returns the student_address of this primary school student.
	 *
	 * @return the student_address of this primary school student
	 */
	@AutoEscape
	public String getStudent_address();

	/**
	 * Sets the student_address of this primary school student.
	 *
	 * @param student_address the student_address of this primary school student
	 */
	public void setStudent_address(String student_address);

	/**
	 * Returns the student_contact name of this primary school student.
	 *
	 * @return the student_contact name of this primary school student
	 */
	@AutoEscape
	public String getStudent_contactName();

	/**
	 * Sets the student_contact name of this primary school student.
	 *
	 * @param student_contactName the student_contact name of this primary school student
	 */
	public void setStudent_contactName(String student_contactName);

	/**
	 * Returns the student_contact relationship of this primary school student.
	 *
	 * @return the student_contact relationship of this primary school student
	 */
	@AutoEscape
	public String getStudent_contactRelationship();

	/**
	 * Sets the student_contact relationship of this primary school student.
	 *
	 * @param student_contactRelationship the student_contact relationship of this primary school student
	 */
	public void setStudent_contactRelationship(
		String student_contactRelationship);

	/**
	 * Returns the student_contact phone number of this primary school student.
	 *
	 * @return the student_contact phone number of this primary school student
	 */
	@AutoEscape
	public String getStudent_contactPhoneNumber();

	/**
	 * Sets the student_contact phone number of this primary school student.
	 *
	 * @param student_contactPhoneNumber the student_contact phone number of this primary school student
	 */
	public void setStudent_contactPhoneNumber(String student_contactPhoneNumber);

	/**
	 * Returns the student_contact email of this primary school student.
	 *
	 * @return the student_contact email of this primary school student
	 */
	@AutoEscape
	public String getStudent_contactEmail();

	/**
	 * Sets the student_contact email of this primary school student.
	 *
	 * @param student_contactEmail the student_contact email of this primary school student
	 */
	public void setStudent_contactEmail(String student_contactEmail);

	/**
	 * Returns the student_school name of this primary school student.
	 *
	 * @return the student_school name of this primary school student
	 */
	@AutoEscape
	public String getStudent_schoolName();

	/**
	 * Sets the student_school name of this primary school student.
	 *
	 * @param student_schoolName the student_school name of this primary school student
	 */
	public void setStudent_schoolName(String student_schoolName);

	/**
	 * Returns the student_school year of this primary school student.
	 *
	 * @return the student_school year of this primary school student
	 */
	@AutoEscape
	public String getStudent_schoolYear();

	/**
	 * Sets the student_school year of this primary school student.
	 *
	 * @param student_schoolYear the student_school year of this primary school student
	 */
	public void setStudent_schoolYear(String student_schoolYear);

	/**
	 * Returns the student_academic level of this primary school student.
	 *
	 * @return the student_academic level of this primary school student
	 */
	@AutoEscape
	public String getStudent_academicLevel();

	/**
	 * Sets the student_academic level of this primary school student.
	 *
	 * @param student_academicLevel the student_academic level of this primary school student
	 */
	public void setStudent_academicLevel(String student_academicLevel);

	/**
	 * Returns the student_studied language of this primary school student.
	 *
	 * @return the student_studied language of this primary school student
	 */
	@AutoEscape
	public String getStudent_studiedLanguage();

	/**
	 * Sets the student_studied language of this primary school student.
	 *
	 * @param student_studiedLanguage the student_studied language of this primary school student
	 */
	public void setStudent_studiedLanguage(String student_studiedLanguage);

	/**
	 * Returns the student_language center of this primary school student.
	 *
	 * @return the student_language center of this primary school student
	 */
	@AutoEscape
	public String getStudent_languageCenter();

	/**
	 * Sets the student_language center of this primary school student.
	 *
	 * @param student_languageCenter the student_language center of this primary school student
	 */
	public void setStudent_languageCenter(String student_languageCenter);

	/**
	 * Returns the student_prizes of this primary school student.
	 *
	 * @return the student_prizes of this primary school student
	 */
	@AutoEscape
	public String getStudent_prizes();

	/**
	 * Sets the student_prizes of this primary school student.
	 *
	 * @param student_prizes the student_prizes of this primary school student
	 */
	public void setStudent_prizes(String student_prizes);

	/**
	 * Returns the student_skipped grade of this primary school student.
	 *
	 * @return the student_skipped grade of this primary school student
	 */
	@AutoEscape
	public String getStudent_skippedGrade();

	/**
	 * Sets the student_skipped grade of this primary school student.
	 *
	 * @param student_skippedGrade the student_skipped grade of this primary school student
	 */
	public void setStudent_skippedGrade(String student_skippedGrade);

	/**
	 * Returns the student_penalty of this primary school student.
	 *
	 * @return the student_penalty of this primary school student
	 */
	@AutoEscape
	public String getStudent_penalty();

	/**
	 * Sets the student_penalty of this primary school student.
	 *
	 * @param student_penalty the student_penalty of this primary school student
	 */
	public void setStudent_penalty(String student_penalty);

	/**
	 * Returns the student_interests of this primary school student.
	 *
	 * @return the student_interests of this primary school student
	 */
	@AutoEscape
	public String getStudent_interests();

	/**
	 * Sets the student_interests of this primary school student.
	 *
	 * @param student_interests the student_interests of this primary school student
	 */
	public void setStudent_interests(String student_interests);

	/**
	 * Returns the student_note of this primary school student.
	 *
	 * @return the student_note of this primary school student
	 */
	@AutoEscape
	public String getStudent_note();

	/**
	 * Sets the student_note of this primary school student.
	 *
	 * @param student_note the student_note of this primary school student
	 */
	public void setStudent_note(String student_note);

	/**
	 * Returns the student_registration class of this primary school student.
	 *
	 * @return the student_registration class of this primary school student
	 */
	@AutoEscape
	public String getStudent_registrationClass();

	/**
	 * Sets the student_registration class of this primary school student.
	 *
	 * @param student_registrationClass the student_registration class of this primary school student
	 */
	public void setStudent_registrationClass(String student_registrationClass);

	/**
	 * Returns the student_expected enroll time of this primary school student.
	 *
	 * @return the student_expected enroll time of this primary school student
	 */
	@AutoEscape
	public String getStudent_expectedEnrollTime();

	/**
	 * Sets the student_expected enroll time of this primary school student.
	 *
	 * @param student_expectedEnrollTime the student_expected enroll time of this primary school student
	 */
	public void setStudent_expectedEnrollTime(String student_expectedEnrollTime);

	/**
	 * Returns the student_user car of this primary school student.
	 *
	 * @return the student_user car of this primary school student
	 */
	@AutoEscape
	public String getStudent_userCar();

	/**
	 * Sets the student_user car of this primary school student.
	 *
	 * @param student_userCar the student_user car of this primary school student
	 */
	public void setStudent_userCar(String student_userCar);

	/**
	 * Returns the student_the light club of this primary school student.
	 *
	 * @return the student_the light club of this primary school student
	 */
	@AutoEscape
	public String getStudent_theLightClub();

	/**
	 * Sets the student_the light club of this primary school student.
	 *
	 * @param student_theLightClub the student_the light club of this primary school student
	 */
	public void setStudent_theLightClub(String student_theLightClub);

	/**
	 * Returns the student_oversea of this primary school student.
	 *
	 * @return the student_oversea of this primary school student
	 */
	@AutoEscape
	public String getStudent_oversea();

	/**
	 * Sets the student_oversea of this primary school student.
	 *
	 * @param student_oversea the student_oversea of this primary school student
	 */
	public void setStudent_oversea(String student_oversea);

	/**
	 * Returns the student_how to know b m of this primary school student.
	 *
	 * @return the student_how to know b m of this primary school student
	 */
	@AutoEscape
	public String getStudent_howToKnowBM();

	/**
	 * Sets the student_how to know b m of this primary school student.
	 *
	 * @param student_howToKnowBM the student_how to know b m of this primary school student
	 */
	public void setStudent_howToKnowBM(String student_howToKnowBM);

	/**
	 * Returns the student_who introduce of this primary school student.
	 *
	 * @return the student_who introduce of this primary school student
	 */
	@AutoEscape
	public String getStudent_whoIntroduce();

	/**
	 * Sets the student_who introduce of this primary school student.
	 *
	 * @param student_whoIntroduce the student_who introduce of this primary school student
	 */
	public void setStudent_whoIntroduce(String student_whoIntroduce);

	/**
	 * Returns the student_any confuse of this primary school student.
	 *
	 * @return the student_any confuse of this primary school student
	 */
	@AutoEscape
	public String getStudent_anyConfuse();

	/**
	 * Sets the student_any confuse of this primary school student.
	 *
	 * @param student_anyConfuse the student_any confuse of this primary school student
	 */
	public void setStudent_anyConfuse(String student_anyConfuse);

	/**
	 * Returns the status of this primary school student.
	 *
	 * @return the status of this primary school student
	 */
	@AutoEscape
	public String getStatus();

	/**
	 * Sets the status of this primary school student.
	 *
	 * @param status the status of this primary school student
	 */
	public void setStatus(String status);

	/**
	 * Returns the created_date of this primary school student.
	 *
	 * @return the created_date of this primary school student
	 */
	public Date getCreated_date();

	/**
	 * Sets the created_date of this primary school student.
	 *
	 * @param created_date the created_date of this primary school student
	 */
	public void setCreated_date(Date created_date);

	/**
	 * Returns the modified_date of this primary school student.
	 *
	 * @return the modified_date of this primary school student
	 */
	public Date getModified_date();

	/**
	 * Sets the modified_date of this primary school student.
	 *
	 * @param modified_date the modified_date of this primary school student
	 */
	public void setModified_date(Date modified_date);

	/**
	 * Returns the deleted of this primary school student.
	 *
	 * @return the deleted of this primary school student
	 */
	public boolean getDeleted();

	/**
	 * Returns <code>true</code> if this primary school student is deleted.
	 *
	 * @return <code>true</code> if this primary school student is deleted; <code>false</code> otherwise
	 */
	public boolean isDeleted();

	/**
	 * Sets whether this primary school student is deleted.
	 *
	 * @param deleted the deleted of this primary school student
	 */
	public void setDeleted(boolean deleted);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(PrimarySchoolStudent primarySchoolStudent);

	public int hashCode();

	public CacheModel<PrimarySchoolStudent> toCacheModel();

	public PrimarySchoolStudent toEscapedModel();

	public String toString();

	public String toXmlString();
}