/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.fsoft.bn.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Question service. Represents a row in the &quot;BN_Question&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.fsoft.bn.model.impl.QuestionModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.fsoft.bn.model.impl.QuestionImpl}.
 * </p>
 *
 * @author FSOFT
 * @see Question
 * @see com.fsoft.bn.model.impl.QuestionImpl
 * @see com.fsoft.bn.model.impl.QuestionModelImpl
 * @generated
 */
public interface QuestionModel extends BaseModel<Question> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a question model instance should use the {@link Question} interface instead.
	 */

	/**
	 * Returns the primary key of this question.
	 *
	 * @return the primary key of this question
	 */
	public String getPrimaryKey();

	/**
	 * Sets the primary key of this question.
	 *
	 * @param primaryKey the primary key of this question
	 */
	public void setPrimaryKey(String primaryKey);

	/**
	 * Returns the question_id of this question.
	 *
	 * @return the question_id of this question
	 */
	@AutoEscape
	public String getQuestion_id();

	/**
	 * Sets the question_id of this question.
	 *
	 * @param question_id the question_id of this question
	 */
	public void setQuestion_id(String question_id);

	/**
	 * Returns the question_title of this question.
	 *
	 * @return the question_title of this question
	 */
	@AutoEscape
	public String getQuestion_title();

	/**
	 * Sets the question_title of this question.
	 *
	 * @param question_title the question_title of this question
	 */
	public void setQuestion_title(String question_title);

	/**
	 * Returns the question_type_id of this question.
	 *
	 * @return the question_type_id of this question
	 */
	@AutoEscape
	public String getQuestion_type_id();

	/**
	 * Sets the question_type_id of this question.
	 *
	 * @param question_type_id the question_type_id of this question
	 */
	public void setQuestion_type_id(String question_type_id);

	/**
	 * Returns the question_content of this question.
	 *
	 * @return the question_content of this question
	 */
	@AutoEscape
	public String getQuestion_content();

	/**
	 * Sets the question_content of this question.
	 *
	 * @param question_content the question_content of this question
	 */
	public void setQuestion_content(String question_content);

	/**
	 * Returns the citizen_name of this question.
	 *
	 * @return the citizen_name of this question
	 */
	@AutoEscape
	public String getCitizen_name();

	/**
	 * Sets the citizen_name of this question.
	 *
	 * @param citizen_name the citizen_name of this question
	 */
	public void setCitizen_name(String citizen_name);

	/**
	 * Returns the citizen_mail of this question.
	 *
	 * @return the citizen_mail of this question
	 */
	@AutoEscape
	public String getCitizen_mail();

	/**
	 * Sets the citizen_mail of this question.
	 *
	 * @param citizen_mail the citizen_mail of this question
	 */
	public void setCitizen_mail(String citizen_mail);

	/**
	 * Returns the citizen_phone of this question.
	 *
	 * @return the citizen_phone of this question
	 */
	@AutoEscape
	public String getCitizen_phone();

	/**
	 * Sets the citizen_phone of this question.
	 *
	 * @param citizen_phone the citizen_phone of this question
	 */
	public void setCitizen_phone(String citizen_phone);

	/**
	 * Returns the citizen_address of this question.
	 *
	 * @return the citizen_address of this question
	 */
	@AutoEscape
	public String getCitizen_address();

	/**
	 * Sets the citizen_address of this question.
	 *
	 * @param citizen_address the citizen_address of this question
	 */
	public void setCitizen_address(String citizen_address);

	/**
	 * Returns the question_status_id of this question.
	 *
	 * @return the question_status_id of this question
	 */
	@AutoEscape
	public String getQuestion_status_id();

	/**
	 * Sets the question_status_id of this question.
	 *
	 * @param question_status_id the question_status_id of this question
	 */
	public void setQuestion_status_id(String question_status_id);

	/**
	 * Returns the answer_id of this question.
	 *
	 * @return the answer_id of this question
	 */
	@AutoEscape
	public String getAnswer_id();

	/**
	 * Sets the answer_id of this question.
	 *
	 * @param answer_id the answer_id of this question
	 */
	public void setAnswer_id(String answer_id);

	/**
	 * Returns the created_date of this question.
	 *
	 * @return the created_date of this question
	 */
	public Date getCreated_date();

	/**
	 * Sets the created_date of this question.
	 *
	 * @param created_date the created_date of this question
	 */
	public void setCreated_date(Date created_date);

	/**
	 * Returns the modified_date of this question.
	 *
	 * @return the modified_date of this question
	 */
	public Date getModified_date();

	/**
	 * Sets the modified_date of this question.
	 *
	 * @param modified_date the modified_date of this question
	 */
	public void setModified_date(Date modified_date);

	/**
	 * Returns the deleted of this question.
	 *
	 * @return the deleted of this question
	 */
	public boolean getDeleted();

	/**
	 * Returns <code>true</code> if this question is deleted.
	 *
	 * @return <code>true</code> if this question is deleted; <code>false</code> otherwise
	 */
	public boolean isDeleted();

	/**
	 * Sets whether this question is deleted.
	 *
	 * @param deleted the deleted of this question
	 */
	public void setDeleted(boolean deleted);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(Question question);

	public int hashCode();

	public CacheModel<Question> toCacheModel();

	public Question toEscapedModel();

	public String toString();

	public String toXmlString();
}