/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.fsoft.bn.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the RecruitmentEducationalHistory service. Represents a row in the &quot;BN_RecruitmentEducationalHistory&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.fsoft.bn.model.impl.RecruitmentEducationalHistoryModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.fsoft.bn.model.impl.RecruitmentEducationalHistoryImpl}.
 * </p>
 *
 * @author FSOFT
 * @see RecruitmentEducationalHistory
 * @see com.fsoft.bn.model.impl.RecruitmentEducationalHistoryImpl
 * @see com.fsoft.bn.model.impl.RecruitmentEducationalHistoryModelImpl
 * @generated
 */
public interface RecruitmentEducationalHistoryModel extends BaseModel<RecruitmentEducationalHistory> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a recruitment educational history model instance should use the {@link RecruitmentEducationalHistory} interface instead.
	 */

	/**
	 * Returns the primary key of this recruitment educational history.
	 *
	 * @return the primary key of this recruitment educational history
	 */
	public String getPrimaryKey();

	/**
	 * Sets the primary key of this recruitment educational history.
	 *
	 * @param primaryKey the primary key of this recruitment educational history
	 */
	public void setPrimaryKey(String primaryKey);

	/**
	 * Returns the recruitment_educational_history_id of this recruitment educational history.
	 *
	 * @return the recruitment_educational_history_id of this recruitment educational history
	 */
	@AutoEscape
	public String getRecruitment_educational_history_id();

	/**
	 * Sets the recruitment_educational_history_id of this recruitment educational history.
	 *
	 * @param recruitment_educational_history_id the recruitment_educational_history_id of this recruitment educational history
	 */
	public void setRecruitment_educational_history_id(
		String recruitment_educational_history_id);

	/**
	 * Returns the recruitment_id of this recruitment educational history.
	 *
	 * @return the recruitment_id of this recruitment educational history
	 */
	@AutoEscape
	public String getRecruitment_id();

	/**
	 * Sets the recruitment_id of this recruitment educational history.
	 *
	 * @param recruitment_id the recruitment_id of this recruitment educational history
	 */
	public void setRecruitment_id(String recruitment_id);

	/**
	 * Returns the school of this recruitment educational history.
	 *
	 * @return the school of this recruitment educational history
	 */
	@AutoEscape
	public String getSchool();

	/**
	 * Sets the school of this recruitment educational history.
	 *
	 * @param school the school of this recruitment educational history
	 */
	public void setSchool(String school);

	/**
	 * Returns the type of training of this recruitment educational history.
	 *
	 * @return the type of training of this recruitment educational history
	 */
	@AutoEscape
	public String getTypeOfTraining();

	/**
	 * Sets the type of training of this recruitment educational history.
	 *
	 * @param typeOfTraining the type of training of this recruitment educational history
	 */
	public void setTypeOfTraining(String typeOfTraining);

	/**
	 * Returns the speciality of this recruitment educational history.
	 *
	 * @return the speciality of this recruitment educational history
	 */
	@AutoEscape
	public String getSpeciality();

	/**
	 * Sets the speciality of this recruitment educational history.
	 *
	 * @param speciality the speciality of this recruitment educational history
	 */
	public void setSpeciality(String speciality);

	/**
	 * Returns the type of degree of this recruitment educational history.
	 *
	 * @return the type of degree of this recruitment educational history
	 */
	@AutoEscape
	public String getTypeOfDegree();

	/**
	 * Sets the type of degree of this recruitment educational history.
	 *
	 * @param typeOfDegree the type of degree of this recruitment educational history
	 */
	public void setTypeOfDegree(String typeOfDegree);

	/**
	 * Returns the graduated year of this recruitment educational history.
	 *
	 * @return the graduated year of this recruitment educational history
	 */
	@AutoEscape
	public String getGraduatedYear();

	/**
	 * Sets the graduated year of this recruitment educational history.
	 *
	 * @param graduatedYear the graduated year of this recruitment educational history
	 */
	public void setGraduatedYear(String graduatedYear);

	/**
	 * Returns the created_date of this recruitment educational history.
	 *
	 * @return the created_date of this recruitment educational history
	 */
	public Date getCreated_date();

	/**
	 * Sets the created_date of this recruitment educational history.
	 *
	 * @param created_date the created_date of this recruitment educational history
	 */
	public void setCreated_date(Date created_date);

	/**
	 * Returns the modified_date of this recruitment educational history.
	 *
	 * @return the modified_date of this recruitment educational history
	 */
	public Date getModified_date();

	/**
	 * Sets the modified_date of this recruitment educational history.
	 *
	 * @param modified_date the modified_date of this recruitment educational history
	 */
	public void setModified_date(Date modified_date);

	/**
	 * Returns the deleted of this recruitment educational history.
	 *
	 * @return the deleted of this recruitment educational history
	 */
	public boolean getDeleted();

	/**
	 * Returns <code>true</code> if this recruitment educational history is deleted.
	 *
	 * @return <code>true</code> if this recruitment educational history is deleted; <code>false</code> otherwise
	 */
	public boolean isDeleted();

	/**
	 * Sets whether this recruitment educational history is deleted.
	 *
	 * @param deleted the deleted of this recruitment educational history
	 */
	public void setDeleted(boolean deleted);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(
		RecruitmentEducationalHistory recruitmentEducationalHistory);

	public int hashCode();

	public CacheModel<RecruitmentEducationalHistory> toCacheModel();

	public RecruitmentEducationalHistory toEscapedModel();

	public String toString();

	public String toXmlString();
}