/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.fsoft.bn.model.impl;

import com.fsoft.bn.model.EnrolmentAttachedFile;
import com.fsoft.bn.model.EnrolmentAttachedFileModel;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the EnrolmentAttachedFile service. Represents a row in the &quot;BN_EnrolmentAttachedFile&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.fsoft.bn.model.EnrolmentAttachedFileModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link EnrolmentAttachedFileImpl}.
 * </p>
 *
 * @author FSOFT
 * @see EnrolmentAttachedFileImpl
 * @see com.fsoft.bn.model.EnrolmentAttachedFile
 * @see com.fsoft.bn.model.EnrolmentAttachedFileModel
 * @generated
 */
public class EnrolmentAttachedFileModelImpl extends BaseModelImpl<EnrolmentAttachedFile>
	implements EnrolmentAttachedFileModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a enrolment attached file model instance should use the {@link com.fsoft.bn.model.EnrolmentAttachedFile} interface instead.
	 */
	public static final String TABLE_NAME = "BN_EnrolmentAttachedFile";
	public static final Object[][] TABLE_COLUMNS = {
			{ "enrolment_attached_id", Types.VARCHAR },
			{ "enrolment_id", Types.VARCHAR },
			{ "attached_file_id", Types.VARCHAR },
			{ "created_date", Types.TIMESTAMP },
			{ "modified_date", Types.TIMESTAMP },
			{ "deleted", Types.BOOLEAN }
		};
	public static final String TABLE_SQL_CREATE = "create table BN_EnrolmentAttachedFile (enrolment_attached_id VARCHAR(75) not null primary key,enrolment_id VARCHAR(75) null,attached_file_id VARCHAR(75) null,created_date DATE null,modified_date DATE null,deleted BOOLEAN)";
	public static final String TABLE_SQL_DROP = "drop table BN_EnrolmentAttachedFile";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.fsoft.bn.model.EnrolmentAttachedFile"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.fsoft.bn.model.EnrolmentAttachedFile"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.fsoft.bn.model.EnrolmentAttachedFile"));

	public EnrolmentAttachedFileModelImpl() {
	}

	public String getPrimaryKey() {
		return _enrolment_attached_id;
	}

	public void setPrimaryKey(String primaryKey) {
		setEnrolment_attached_id(primaryKey);
	}

	public Serializable getPrimaryKeyObj() {
		return _enrolment_attached_id;
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey((String)primaryKeyObj);
	}

	public Class<?> getModelClass() {
		return EnrolmentAttachedFile.class;
	}

	public String getModelClassName() {
		return EnrolmentAttachedFile.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("enrolment_attached_id", getEnrolment_attached_id());
		attributes.put("enrolment_id", getEnrolment_id());
		attributes.put("attached_file_id", getAttached_file_id());
		attributes.put("created_date", getCreated_date());
		attributes.put("modified_date", getModified_date());
		attributes.put("deleted", getDeleted());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		String enrolment_attached_id = (String)attributes.get(
				"enrolment_attached_id");

		if (enrolment_attached_id != null) {
			setEnrolment_attached_id(enrolment_attached_id);
		}

		String enrolment_id = (String)attributes.get("enrolment_id");

		if (enrolment_id != null) {
			setEnrolment_id(enrolment_id);
		}

		String attached_file_id = (String)attributes.get("attached_file_id");

		if (attached_file_id != null) {
			setAttached_file_id(attached_file_id);
		}

		Date created_date = (Date)attributes.get("created_date");

		if (created_date != null) {
			setCreated_date(created_date);
		}

		Date modified_date = (Date)attributes.get("modified_date");

		if (modified_date != null) {
			setModified_date(modified_date);
		}

		Boolean deleted = (Boolean)attributes.get("deleted");

		if (deleted != null) {
			setDeleted(deleted);
		}
	}

	public String getEnrolment_attached_id() {
		if (_enrolment_attached_id == null) {
			return StringPool.BLANK;
		}
		else {
			return _enrolment_attached_id;
		}
	}

	public void setEnrolment_attached_id(String enrolment_attached_id) {
		_enrolment_attached_id = enrolment_attached_id;
	}

	public String getEnrolment_id() {
		if (_enrolment_id == null) {
			return StringPool.BLANK;
		}
		else {
			return _enrolment_id;
		}
	}

	public void setEnrolment_id(String enrolment_id) {
		_enrolment_id = enrolment_id;
	}

	public String getAttached_file_id() {
		if (_attached_file_id == null) {
			return StringPool.BLANK;
		}
		else {
			return _attached_file_id;
		}
	}

	public void setAttached_file_id(String attached_file_id) {
		_attached_file_id = attached_file_id;
	}

	public Date getCreated_date() {
		return _created_date;
	}

	public void setCreated_date(Date created_date) {
		_created_date = created_date;
	}

	public Date getModified_date() {
		return _modified_date;
	}

	public void setModified_date(Date modified_date) {
		_modified_date = modified_date;
	}

	public boolean getDeleted() {
		return _deleted;
	}

	public boolean isDeleted() {
		return _deleted;
	}

	public void setDeleted(boolean deleted) {
		_deleted = deleted;
	}

	@Override
	public EnrolmentAttachedFile toEscapedModel() {
		if (_escapedModelProxy == null) {
			_escapedModelProxy = (EnrolmentAttachedFile)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelProxyInterfaces,
					new AutoEscapeBeanHandler(this));
		}

		return _escapedModelProxy;
	}

	@Override
	public Object clone() {
		EnrolmentAttachedFileImpl enrolmentAttachedFileImpl = new EnrolmentAttachedFileImpl();

		enrolmentAttachedFileImpl.setEnrolment_attached_id(getEnrolment_attached_id());
		enrolmentAttachedFileImpl.setEnrolment_id(getEnrolment_id());
		enrolmentAttachedFileImpl.setAttached_file_id(getAttached_file_id());
		enrolmentAttachedFileImpl.setCreated_date(getCreated_date());
		enrolmentAttachedFileImpl.setModified_date(getModified_date());
		enrolmentAttachedFileImpl.setDeleted(getDeleted());

		enrolmentAttachedFileImpl.resetOriginalValues();

		return enrolmentAttachedFileImpl;
	}

	public int compareTo(EnrolmentAttachedFile enrolmentAttachedFile) {
		String primaryKey = enrolmentAttachedFile.getPrimaryKey();

		return getPrimaryKey().compareTo(primaryKey);
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		EnrolmentAttachedFile enrolmentAttachedFile = null;

		try {
			enrolmentAttachedFile = (EnrolmentAttachedFile)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		String primaryKey = enrolmentAttachedFile.getPrimaryKey();

		if (getPrimaryKey().equals(primaryKey)) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey().hashCode();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<EnrolmentAttachedFile> toCacheModel() {
		EnrolmentAttachedFileCacheModel enrolmentAttachedFileCacheModel = new EnrolmentAttachedFileCacheModel();

		enrolmentAttachedFileCacheModel.enrolment_attached_id = getEnrolment_attached_id();

		String enrolment_attached_id = enrolmentAttachedFileCacheModel.enrolment_attached_id;

		if ((enrolment_attached_id != null) &&
				(enrolment_attached_id.length() == 0)) {
			enrolmentAttachedFileCacheModel.enrolment_attached_id = null;
		}

		enrolmentAttachedFileCacheModel.enrolment_id = getEnrolment_id();

		String enrolment_id = enrolmentAttachedFileCacheModel.enrolment_id;

		if ((enrolment_id != null) && (enrolment_id.length() == 0)) {
			enrolmentAttachedFileCacheModel.enrolment_id = null;
		}

		enrolmentAttachedFileCacheModel.attached_file_id = getAttached_file_id();

		String attached_file_id = enrolmentAttachedFileCacheModel.attached_file_id;

		if ((attached_file_id != null) && (attached_file_id.length() == 0)) {
			enrolmentAttachedFileCacheModel.attached_file_id = null;
		}

		Date created_date = getCreated_date();

		if (created_date != null) {
			enrolmentAttachedFileCacheModel.created_date = created_date.getTime();
		}
		else {
			enrolmentAttachedFileCacheModel.created_date = Long.MIN_VALUE;
		}

		Date modified_date = getModified_date();

		if (modified_date != null) {
			enrolmentAttachedFileCacheModel.modified_date = modified_date.getTime();
		}
		else {
			enrolmentAttachedFileCacheModel.modified_date = Long.MIN_VALUE;
		}

		enrolmentAttachedFileCacheModel.deleted = getDeleted();

		return enrolmentAttachedFileCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(13);

		sb.append("{enrolment_attached_id=");
		sb.append(getEnrolment_attached_id());
		sb.append(", enrolment_id=");
		sb.append(getEnrolment_id());
		sb.append(", attached_file_id=");
		sb.append(getAttached_file_id());
		sb.append(", created_date=");
		sb.append(getCreated_date());
		sb.append(", modified_date=");
		sb.append(getModified_date());
		sb.append(", deleted=");
		sb.append(getDeleted());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(22);

		sb.append("<model><model-name>");
		sb.append("com.fsoft.bn.model.EnrolmentAttachedFile");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>enrolment_attached_id</column-name><column-value><![CDATA[");
		sb.append(getEnrolment_attached_id());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>enrolment_id</column-name><column-value><![CDATA[");
		sb.append(getEnrolment_id());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>attached_file_id</column-name><column-value><![CDATA[");
		sb.append(getAttached_file_id());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>created_date</column-name><column-value><![CDATA[");
		sb.append(getCreated_date());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modified_date</column-name><column-value><![CDATA[");
		sb.append(getModified_date());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>deleted</column-name><column-value><![CDATA[");
		sb.append(getDeleted());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = EnrolmentAttachedFile.class.getClassLoader();
	private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
			EnrolmentAttachedFile.class
		};
	private String _enrolment_attached_id;
	private String _enrolment_id;
	private String _attached_file_id;
	private Date _created_date;
	private Date _modified_date;
	private boolean _deleted;
	private EnrolmentAttachedFile _escapedModelProxy;
}