/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.fsoft.bn.model.impl;

import com.fsoft.bn.model.PreschoolAttachedFile;
import com.fsoft.bn.model.PreschoolAttachedFileModel;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the PreschoolAttachedFile service. Represents a row in the &quot;BN_PreschoolAttachedFile&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.fsoft.bn.model.PreschoolAttachedFileModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link PreschoolAttachedFileImpl}.
 * </p>
 *
 * @author FSOFT
 * @see PreschoolAttachedFileImpl
 * @see com.fsoft.bn.model.PreschoolAttachedFile
 * @see com.fsoft.bn.model.PreschoolAttachedFileModel
 * @generated
 */
public class PreschoolAttachedFileModelImpl extends BaseModelImpl<PreschoolAttachedFile>
	implements PreschoolAttachedFileModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a preschool attached file model instance should use the {@link com.fsoft.bn.model.PreschoolAttachedFile} interface instead.
	 */
	public static final String TABLE_NAME = "BN_PreschoolAttachedFile";
	public static final Object[][] TABLE_COLUMNS = {
			{ "preschool_attached_id", Types.VARCHAR },
			{ "student_id", Types.VARCHAR },
			{ "attached_file_id", Types.VARCHAR },
			{ "created_date", Types.TIMESTAMP },
			{ "modified_date", Types.TIMESTAMP },
			{ "deleted", Types.BOOLEAN }
		};
	public static final String TABLE_SQL_CREATE = "create table BN_PreschoolAttachedFile (preschool_attached_id VARCHAR(75) not null primary key,student_id VARCHAR(75) null,attached_file_id VARCHAR(75) null,created_date DATE null,modified_date DATE null,deleted BOOLEAN)";
	public static final String TABLE_SQL_DROP = "drop table BN_PreschoolAttachedFile";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.fsoft.bn.model.PreschoolAttachedFile"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.fsoft.bn.model.PreschoolAttachedFile"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.fsoft.bn.model.PreschoolAttachedFile"));

	public PreschoolAttachedFileModelImpl() {
	}

	public String getPrimaryKey() {
		return _preschool_attached_id;
	}

	public void setPrimaryKey(String primaryKey) {
		setPreschool_attached_id(primaryKey);
	}

	public Serializable getPrimaryKeyObj() {
		return _preschool_attached_id;
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey((String)primaryKeyObj);
	}

	public Class<?> getModelClass() {
		return PreschoolAttachedFile.class;
	}

	public String getModelClassName() {
		return PreschoolAttachedFile.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("preschool_attached_id", getPreschool_attached_id());
		attributes.put("student_id", getStudent_id());
		attributes.put("attached_file_id", getAttached_file_id());
		attributes.put("created_date", getCreated_date());
		attributes.put("modified_date", getModified_date());
		attributes.put("deleted", getDeleted());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		String preschool_attached_id = (String)attributes.get(
				"preschool_attached_id");

		if (preschool_attached_id != null) {
			setPreschool_attached_id(preschool_attached_id);
		}

		String student_id = (String)attributes.get("student_id");

		if (student_id != null) {
			setStudent_id(student_id);
		}

		String attached_file_id = (String)attributes.get("attached_file_id");

		if (attached_file_id != null) {
			setAttached_file_id(attached_file_id);
		}

		Date created_date = (Date)attributes.get("created_date");

		if (created_date != null) {
			setCreated_date(created_date);
		}

		Date modified_date = (Date)attributes.get("modified_date");

		if (modified_date != null) {
			setModified_date(modified_date);
		}

		Boolean deleted = (Boolean)attributes.get("deleted");

		if (deleted != null) {
			setDeleted(deleted);
		}
	}

	public String getPreschool_attached_id() {
		if (_preschool_attached_id == null) {
			return StringPool.BLANK;
		}
		else {
			return _preschool_attached_id;
		}
	}

	public void setPreschool_attached_id(String preschool_attached_id) {
		_preschool_attached_id = preschool_attached_id;
	}

	public String getStudent_id() {
		if (_student_id == null) {
			return StringPool.BLANK;
		}
		else {
			return _student_id;
		}
	}

	public void setStudent_id(String student_id) {
		_student_id = student_id;
	}

	public String getAttached_file_id() {
		if (_attached_file_id == null) {
			return StringPool.BLANK;
		}
		else {
			return _attached_file_id;
		}
	}

	public void setAttached_file_id(String attached_file_id) {
		_attached_file_id = attached_file_id;
	}

	public Date getCreated_date() {
		return _created_date;
	}

	public void setCreated_date(Date created_date) {
		_created_date = created_date;
	}

	public Date getModified_date() {
		return _modified_date;
	}

	public void setModified_date(Date modified_date) {
		_modified_date = modified_date;
	}

	public boolean getDeleted() {
		return _deleted;
	}

	public boolean isDeleted() {
		return _deleted;
	}

	public void setDeleted(boolean deleted) {
		_deleted = deleted;
	}

	@Override
	public PreschoolAttachedFile toEscapedModel() {
		if (_escapedModelProxy == null) {
			_escapedModelProxy = (PreschoolAttachedFile)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelProxyInterfaces,
					new AutoEscapeBeanHandler(this));
		}

		return _escapedModelProxy;
	}

	@Override
	public Object clone() {
		PreschoolAttachedFileImpl preschoolAttachedFileImpl = new PreschoolAttachedFileImpl();

		preschoolAttachedFileImpl.setPreschool_attached_id(getPreschool_attached_id());
		preschoolAttachedFileImpl.setStudent_id(getStudent_id());
		preschoolAttachedFileImpl.setAttached_file_id(getAttached_file_id());
		preschoolAttachedFileImpl.setCreated_date(getCreated_date());
		preschoolAttachedFileImpl.setModified_date(getModified_date());
		preschoolAttachedFileImpl.setDeleted(getDeleted());

		preschoolAttachedFileImpl.resetOriginalValues();

		return preschoolAttachedFileImpl;
	}

	public int compareTo(PreschoolAttachedFile preschoolAttachedFile) {
		String primaryKey = preschoolAttachedFile.getPrimaryKey();

		return getPrimaryKey().compareTo(primaryKey);
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		PreschoolAttachedFile preschoolAttachedFile = null;

		try {
			preschoolAttachedFile = (PreschoolAttachedFile)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		String primaryKey = preschoolAttachedFile.getPrimaryKey();

		if (getPrimaryKey().equals(primaryKey)) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey().hashCode();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<PreschoolAttachedFile> toCacheModel() {
		PreschoolAttachedFileCacheModel preschoolAttachedFileCacheModel = new PreschoolAttachedFileCacheModel();

		preschoolAttachedFileCacheModel.preschool_attached_id = getPreschool_attached_id();

		String preschool_attached_id = preschoolAttachedFileCacheModel.preschool_attached_id;

		if ((preschool_attached_id != null) &&
				(preschool_attached_id.length() == 0)) {
			preschoolAttachedFileCacheModel.preschool_attached_id = null;
		}

		preschoolAttachedFileCacheModel.student_id = getStudent_id();

		String student_id = preschoolAttachedFileCacheModel.student_id;

		if ((student_id != null) && (student_id.length() == 0)) {
			preschoolAttachedFileCacheModel.student_id = null;
		}

		preschoolAttachedFileCacheModel.attached_file_id = getAttached_file_id();

		String attached_file_id = preschoolAttachedFileCacheModel.attached_file_id;

		if ((attached_file_id != null) && (attached_file_id.length() == 0)) {
			preschoolAttachedFileCacheModel.attached_file_id = null;
		}

		Date created_date = getCreated_date();

		if (created_date != null) {
			preschoolAttachedFileCacheModel.created_date = created_date.getTime();
		}
		else {
			preschoolAttachedFileCacheModel.created_date = Long.MIN_VALUE;
		}

		Date modified_date = getModified_date();

		if (modified_date != null) {
			preschoolAttachedFileCacheModel.modified_date = modified_date.getTime();
		}
		else {
			preschoolAttachedFileCacheModel.modified_date = Long.MIN_VALUE;
		}

		preschoolAttachedFileCacheModel.deleted = getDeleted();

		return preschoolAttachedFileCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(13);

		sb.append("{preschool_attached_id=");
		sb.append(getPreschool_attached_id());
		sb.append(", student_id=");
		sb.append(getStudent_id());
		sb.append(", attached_file_id=");
		sb.append(getAttached_file_id());
		sb.append(", created_date=");
		sb.append(getCreated_date());
		sb.append(", modified_date=");
		sb.append(getModified_date());
		sb.append(", deleted=");
		sb.append(getDeleted());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(22);

		sb.append("<model><model-name>");
		sb.append("com.fsoft.bn.model.PreschoolAttachedFile");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>preschool_attached_id</column-name><column-value><![CDATA[");
		sb.append(getPreschool_attached_id());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>student_id</column-name><column-value><![CDATA[");
		sb.append(getStudent_id());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>attached_file_id</column-name><column-value><![CDATA[");
		sb.append(getAttached_file_id());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>created_date</column-name><column-value><![CDATA[");
		sb.append(getCreated_date());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modified_date</column-name><column-value><![CDATA[");
		sb.append(getModified_date());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>deleted</column-name><column-value><![CDATA[");
		sb.append(getDeleted());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = PreschoolAttachedFile.class.getClassLoader();
	private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
			PreschoolAttachedFile.class
		};
	private String _preschool_attached_id;
	private String _student_id;
	private String _attached_file_id;
	private Date _created_date;
	private Date _modified_date;
	private boolean _deleted;
	private PreschoolAttachedFile _escapedModelProxy;
}