/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.fsoft.bn.model.impl;

import com.fsoft.bn.model.PreschoolParent;
import com.fsoft.bn.model.PreschoolParentModel;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the PreschoolParent service. Represents a row in the &quot;BN_PreschoolParent&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.fsoft.bn.model.PreschoolParentModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link PreschoolParentImpl}.
 * </p>
 *
 * @author FSOFT
 * @see PreschoolParentImpl
 * @see com.fsoft.bn.model.PreschoolParent
 * @see com.fsoft.bn.model.PreschoolParentModel
 * @generated
 */
public class PreschoolParentModelImpl extends BaseModelImpl<PreschoolParent>
	implements PreschoolParentModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a preschool parent model instance should use the {@link com.fsoft.bn.model.PreschoolParent} interface instead.
	 */
	public static final String TABLE_NAME = "BN_PreschoolParent";
	public static final Object[][] TABLE_COLUMNS = {
			{ "preschoolParent_id", Types.VARCHAR },
			{ "student_id", Types.VARCHAR },
			{ "name", Types.VARCHAR },
			{ "dob", Types.VARCHAR },
			{ "placeOfBirth", Types.VARCHAR },
			{ "nationality", Types.VARCHAR },
			{ "idCardNumber", Types.VARCHAR },
			{ "job", Types.VARCHAR },
			{ "phoneNumber", Types.VARCHAR },
			{ "Email", Types.VARCHAR },
			{ "isMother", Types.BOOLEAN },
			{ "created_date", Types.TIMESTAMP },
			{ "modified_date", Types.TIMESTAMP },
			{ "deleted", Types.BOOLEAN }
		};
	public static final String TABLE_SQL_CREATE = "create table BN_PreschoolParent (preschoolParent_id VARCHAR(75) not null primary key,student_id VARCHAR(75) null,name VARCHAR(75) null,dob VARCHAR(75) null,placeOfBirth VARCHAR(75) null,nationality VARCHAR(75) null,idCardNumber VARCHAR(75) null,job VARCHAR(75) null,phoneNumber VARCHAR(75) null,Email VARCHAR(75) null,isMother BOOLEAN,created_date DATE null,modified_date DATE null,deleted BOOLEAN)";
	public static final String TABLE_SQL_DROP = "drop table BN_PreschoolParent";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.fsoft.bn.model.PreschoolParent"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.fsoft.bn.model.PreschoolParent"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.fsoft.bn.model.PreschoolParent"));

	public PreschoolParentModelImpl() {
	}

	public String getPrimaryKey() {
		return _preschoolParent_id;
	}

	public void setPrimaryKey(String primaryKey) {
		setPreschoolParent_id(primaryKey);
	}

	public Serializable getPrimaryKeyObj() {
		return _preschoolParent_id;
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey((String)primaryKeyObj);
	}

	public Class<?> getModelClass() {
		return PreschoolParent.class;
	}

	public String getModelClassName() {
		return PreschoolParent.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("preschoolParent_id", getPreschoolParent_id());
		attributes.put("student_id", getStudent_id());
		attributes.put("name", getName());
		attributes.put("dob", getDob());
		attributes.put("placeOfBirth", getPlaceOfBirth());
		attributes.put("nationality", getNationality());
		attributes.put("idCardNumber", getIdCardNumber());
		attributes.put("job", getJob());
		attributes.put("phoneNumber", getPhoneNumber());
		attributes.put("Email", getEmail());
		attributes.put("isMother", getIsMother());
		attributes.put("created_date", getCreated_date());
		attributes.put("modified_date", getModified_date());
		attributes.put("deleted", getDeleted());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		String preschoolParent_id = (String)attributes.get("preschoolParent_id");

		if (preschoolParent_id != null) {
			setPreschoolParent_id(preschoolParent_id);
		}

		String student_id = (String)attributes.get("student_id");

		if (student_id != null) {
			setStudent_id(student_id);
		}

		String name = (String)attributes.get("name");

		if (name != null) {
			setName(name);
		}

		String dob = (String)attributes.get("dob");

		if (dob != null) {
			setDob(dob);
		}

		String placeOfBirth = (String)attributes.get("placeOfBirth");

		if (placeOfBirth != null) {
			setPlaceOfBirth(placeOfBirth);
		}

		String nationality = (String)attributes.get("nationality");

		if (nationality != null) {
			setNationality(nationality);
		}

		String idCardNumber = (String)attributes.get("idCardNumber");

		if (idCardNumber != null) {
			setIdCardNumber(idCardNumber);
		}

		String job = (String)attributes.get("job");

		if (job != null) {
			setJob(job);
		}

		String phoneNumber = (String)attributes.get("phoneNumber");

		if (phoneNumber != null) {
			setPhoneNumber(phoneNumber);
		}

		String Email = (String)attributes.get("Email");

		if (Email != null) {
			setEmail(Email);
		}

		Boolean isMother = (Boolean)attributes.get("isMother");

		if (isMother != null) {
			setIsMother(isMother);
		}

		Date created_date = (Date)attributes.get("created_date");

		if (created_date != null) {
			setCreated_date(created_date);
		}

		Date modified_date = (Date)attributes.get("modified_date");

		if (modified_date != null) {
			setModified_date(modified_date);
		}

		Boolean deleted = (Boolean)attributes.get("deleted");

		if (deleted != null) {
			setDeleted(deleted);
		}
	}

	public String getPreschoolParent_id() {
		if (_preschoolParent_id == null) {
			return StringPool.BLANK;
		}
		else {
			return _preschoolParent_id;
		}
	}

	public void setPreschoolParent_id(String preschoolParent_id) {
		_preschoolParent_id = preschoolParent_id;
	}

	public String getStudent_id() {
		if (_student_id == null) {
			return StringPool.BLANK;
		}
		else {
			return _student_id;
		}
	}

	public void setStudent_id(String student_id) {
		_student_id = student_id;
	}

	public String getName() {
		if (_name == null) {
			return StringPool.BLANK;
		}
		else {
			return _name;
		}
	}

	public void setName(String name) {
		_name = name;
	}

	public String getDob() {
		if (_dob == null) {
			return StringPool.BLANK;
		}
		else {
			return _dob;
		}
	}

	public void setDob(String dob) {
		_dob = dob;
	}

	public String getPlaceOfBirth() {
		if (_placeOfBirth == null) {
			return StringPool.BLANK;
		}
		else {
			return _placeOfBirth;
		}
	}

	public void setPlaceOfBirth(String placeOfBirth) {
		_placeOfBirth = placeOfBirth;
	}

	public String getNationality() {
		if (_nationality == null) {
			return StringPool.BLANK;
		}
		else {
			return _nationality;
		}
	}

	public void setNationality(String nationality) {
		_nationality = nationality;
	}

	public String getIdCardNumber() {
		if (_idCardNumber == null) {
			return StringPool.BLANK;
		}
		else {
			return _idCardNumber;
		}
	}

	public void setIdCardNumber(String idCardNumber) {
		_idCardNumber = idCardNumber;
	}

	public String getJob() {
		if (_job == null) {
			return StringPool.BLANK;
		}
		else {
			return _job;
		}
	}

	public void setJob(String job) {
		_job = job;
	}

	public String getPhoneNumber() {
		if (_phoneNumber == null) {
			return StringPool.BLANK;
		}
		else {
			return _phoneNumber;
		}
	}

	public void setPhoneNumber(String phoneNumber) {
		_phoneNumber = phoneNumber;
	}

	public String getEmail() {
		if (_Email == null) {
			return StringPool.BLANK;
		}
		else {
			return _Email;
		}
	}

	public void setEmail(String Email) {
		_Email = Email;
	}

	public boolean getIsMother() {
		return _isMother;
	}

	public boolean isIsMother() {
		return _isMother;
	}

	public void setIsMother(boolean isMother) {
		_isMother = isMother;
	}

	public Date getCreated_date() {
		return _created_date;
	}

	public void setCreated_date(Date created_date) {
		_created_date = created_date;
	}

	public Date getModified_date() {
		return _modified_date;
	}

	public void setModified_date(Date modified_date) {
		_modified_date = modified_date;
	}

	public boolean getDeleted() {
		return _deleted;
	}

	public boolean isDeleted() {
		return _deleted;
	}

	public void setDeleted(boolean deleted) {
		_deleted = deleted;
	}

	@Override
	public PreschoolParent toEscapedModel() {
		if (_escapedModelProxy == null) {
			_escapedModelProxy = (PreschoolParent)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelProxyInterfaces,
					new AutoEscapeBeanHandler(this));
		}

		return _escapedModelProxy;
	}

	@Override
	public Object clone() {
		PreschoolParentImpl preschoolParentImpl = new PreschoolParentImpl();

		preschoolParentImpl.setPreschoolParent_id(getPreschoolParent_id());
		preschoolParentImpl.setStudent_id(getStudent_id());
		preschoolParentImpl.setName(getName());
		preschoolParentImpl.setDob(getDob());
		preschoolParentImpl.setPlaceOfBirth(getPlaceOfBirth());
		preschoolParentImpl.setNationality(getNationality());
		preschoolParentImpl.setIdCardNumber(getIdCardNumber());
		preschoolParentImpl.setJob(getJob());
		preschoolParentImpl.setPhoneNumber(getPhoneNumber());
		preschoolParentImpl.setEmail(getEmail());
		preschoolParentImpl.setIsMother(getIsMother());
		preschoolParentImpl.setCreated_date(getCreated_date());
		preschoolParentImpl.setModified_date(getModified_date());
		preschoolParentImpl.setDeleted(getDeleted());

		preschoolParentImpl.resetOriginalValues();

		return preschoolParentImpl;
	}

	public int compareTo(PreschoolParent preschoolParent) {
		String primaryKey = preschoolParent.getPrimaryKey();

		return getPrimaryKey().compareTo(primaryKey);
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		PreschoolParent preschoolParent = null;

		try {
			preschoolParent = (PreschoolParent)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		String primaryKey = preschoolParent.getPrimaryKey();

		if (getPrimaryKey().equals(primaryKey)) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey().hashCode();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<PreschoolParent> toCacheModel() {
		PreschoolParentCacheModel preschoolParentCacheModel = new PreschoolParentCacheModel();

		preschoolParentCacheModel.preschoolParent_id = getPreschoolParent_id();

		String preschoolParent_id = preschoolParentCacheModel.preschoolParent_id;

		if ((preschoolParent_id != null) && (preschoolParent_id.length() == 0)) {
			preschoolParentCacheModel.preschoolParent_id = null;
		}

		preschoolParentCacheModel.student_id = getStudent_id();

		String student_id = preschoolParentCacheModel.student_id;

		if ((student_id != null) && (student_id.length() == 0)) {
			preschoolParentCacheModel.student_id = null;
		}

		preschoolParentCacheModel.name = getName();

		String name = preschoolParentCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			preschoolParentCacheModel.name = null;
		}

		preschoolParentCacheModel.dob = getDob();

		String dob = preschoolParentCacheModel.dob;

		if ((dob != null) && (dob.length() == 0)) {
			preschoolParentCacheModel.dob = null;
		}

		preschoolParentCacheModel.placeOfBirth = getPlaceOfBirth();

		String placeOfBirth = preschoolParentCacheModel.placeOfBirth;

		if ((placeOfBirth != null) && (placeOfBirth.length() == 0)) {
			preschoolParentCacheModel.placeOfBirth = null;
		}

		preschoolParentCacheModel.nationality = getNationality();

		String nationality = preschoolParentCacheModel.nationality;

		if ((nationality != null) && (nationality.length() == 0)) {
			preschoolParentCacheModel.nationality = null;
		}

		preschoolParentCacheModel.idCardNumber = getIdCardNumber();

		String idCardNumber = preschoolParentCacheModel.idCardNumber;

		if ((idCardNumber != null) && (idCardNumber.length() == 0)) {
			preschoolParentCacheModel.idCardNumber = null;
		}

		preschoolParentCacheModel.job = getJob();

		String job = preschoolParentCacheModel.job;

		if ((job != null) && (job.length() == 0)) {
			preschoolParentCacheModel.job = null;
		}

		preschoolParentCacheModel.phoneNumber = getPhoneNumber();

		String phoneNumber = preschoolParentCacheModel.phoneNumber;

		if ((phoneNumber != null) && (phoneNumber.length() == 0)) {
			preschoolParentCacheModel.phoneNumber = null;
		}

		preschoolParentCacheModel.Email = getEmail();

		String Email = preschoolParentCacheModel.Email;

		if ((Email != null) && (Email.length() == 0)) {
			preschoolParentCacheModel.Email = null;
		}

		preschoolParentCacheModel.isMother = getIsMother();

		Date created_date = getCreated_date();

		if (created_date != null) {
			preschoolParentCacheModel.created_date = created_date.getTime();
		}
		else {
			preschoolParentCacheModel.created_date = Long.MIN_VALUE;
		}

		Date modified_date = getModified_date();

		if (modified_date != null) {
			preschoolParentCacheModel.modified_date = modified_date.getTime();
		}
		else {
			preschoolParentCacheModel.modified_date = Long.MIN_VALUE;
		}

		preschoolParentCacheModel.deleted = getDeleted();

		return preschoolParentCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(29);

		sb.append("{preschoolParent_id=");
		sb.append(getPreschoolParent_id());
		sb.append(", student_id=");
		sb.append(getStudent_id());
		sb.append(", name=");
		sb.append(getName());
		sb.append(", dob=");
		sb.append(getDob());
		sb.append(", placeOfBirth=");
		sb.append(getPlaceOfBirth());
		sb.append(", nationality=");
		sb.append(getNationality());
		sb.append(", idCardNumber=");
		sb.append(getIdCardNumber());
		sb.append(", job=");
		sb.append(getJob());
		sb.append(", phoneNumber=");
		sb.append(getPhoneNumber());
		sb.append(", Email=");
		sb.append(getEmail());
		sb.append(", isMother=");
		sb.append(getIsMother());
		sb.append(", created_date=");
		sb.append(getCreated_date());
		sb.append(", modified_date=");
		sb.append(getModified_date());
		sb.append(", deleted=");
		sb.append(getDeleted());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(46);

		sb.append("<model><model-name>");
		sb.append("com.fsoft.bn.model.PreschoolParent");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>preschoolParent_id</column-name><column-value><![CDATA[");
		sb.append(getPreschoolParent_id());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>student_id</column-name><column-value><![CDATA[");
		sb.append(getStudent_id());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>name</column-name><column-value><![CDATA[");
		sb.append(getName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>dob</column-name><column-value><![CDATA[");
		sb.append(getDob());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>placeOfBirth</column-name><column-value><![CDATA[");
		sb.append(getPlaceOfBirth());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>nationality</column-name><column-value><![CDATA[");
		sb.append(getNationality());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>idCardNumber</column-name><column-value><![CDATA[");
		sb.append(getIdCardNumber());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>job</column-name><column-value><![CDATA[");
		sb.append(getJob());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>phoneNumber</column-name><column-value><![CDATA[");
		sb.append(getPhoneNumber());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>Email</column-name><column-value><![CDATA[");
		sb.append(getEmail());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>isMother</column-name><column-value><![CDATA[");
		sb.append(getIsMother());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>created_date</column-name><column-value><![CDATA[");
		sb.append(getCreated_date());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modified_date</column-name><column-value><![CDATA[");
		sb.append(getModified_date());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>deleted</column-name><column-value><![CDATA[");
		sb.append(getDeleted());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = PreschoolParent.class.getClassLoader();
	private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
			PreschoolParent.class
		};
	private String _preschoolParent_id;
	private String _student_id;
	private String _name;
	private String _dob;
	private String _placeOfBirth;
	private String _nationality;
	private String _idCardNumber;
	private String _job;
	private String _phoneNumber;
	private String _Email;
	private boolean _isMother;
	private Date _created_date;
	private Date _modified_date;
	private boolean _deleted;
	private PreschoolParent _escapedModelProxy;
}