/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.fsoft.bn.model.impl;

import com.fsoft.bn.model.PrimarySchoolStudent;
import com.fsoft.bn.model.PrimarySchoolStudentModel;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the PrimarySchoolStudent service. Represents a row in the &quot;BN_PrimarySchoolStudent&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.fsoft.bn.model.PrimarySchoolStudentModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link PrimarySchoolStudentImpl}.
 * </p>
 *
 * @author FSOFT
 * @see PrimarySchoolStudentImpl
 * @see com.fsoft.bn.model.PrimarySchoolStudent
 * @see com.fsoft.bn.model.PrimarySchoolStudentModel
 * @generated
 */
public class PrimarySchoolStudentModelImpl extends BaseModelImpl<PrimarySchoolStudent>
	implements PrimarySchoolStudentModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a primary school student model instance should use the {@link com.fsoft.bn.model.PrimarySchoolStudent} interface instead.
	 */
	public static final String TABLE_NAME = "BN_PrimarySchoolStudent";
	public static final Object[][] TABLE_COLUMNS = {
			{ "primaryStudent_id", Types.VARCHAR },
			{ "student_name", Types.VARCHAR },
			{ "student_sex", Types.VARCHAR },
			{ "student_dob", Types.VARCHAR },
			{ "student_placeOfBirth", Types.VARCHAR },
			{ "student_nationality", Types.VARCHAR },
			{ "student_address", Types.VARCHAR },
			{ "student_contactName", Types.VARCHAR },
			{ "student_contactRelationship", Types.VARCHAR },
			{ "student_contactPhoneNumber", Types.VARCHAR },
			{ "student_contactEmail", Types.VARCHAR },
			{ "student_schoolName", Types.VARCHAR },
			{ "student_schoolYear", Types.VARCHAR },
			{ "student_academicLevel", Types.VARCHAR },
			{ "student_studiedLanguage", Types.VARCHAR },
			{ "student_languageCenter", Types.VARCHAR },
			{ "student_prizes", Types.VARCHAR },
			{ "student_skippedGrade", Types.VARCHAR },
			{ "student_penalty", Types.VARCHAR },
			{ "student_interests", Types.VARCHAR },
			{ "student_note", Types.VARCHAR },
			{ "student_registrationClass", Types.VARCHAR },
			{ "student_expectedEnrollTime", Types.VARCHAR },
			{ "student_userCar", Types.VARCHAR },
			{ "student_theLightClub", Types.VARCHAR },
			{ "student_oversea", Types.VARCHAR },
			{ "student_howToKnowBM", Types.VARCHAR },
			{ "student_whoIntroduce", Types.VARCHAR },
			{ "student_anyConfuse", Types.VARCHAR },
			{ "status", Types.VARCHAR },
			{ "created_date", Types.TIMESTAMP },
			{ "modified_date", Types.TIMESTAMP },
			{ "deleted", Types.BOOLEAN }
		};
	public static final String TABLE_SQL_CREATE = "create table BN_PrimarySchoolStudent (primaryStudent_id VARCHAR(75) not null primary key,student_name VARCHAR(75) null,student_sex VARCHAR(75) null,student_dob VARCHAR(75) null,student_placeOfBirth VARCHAR(75) null,student_nationality VARCHAR(75) null,student_address VARCHAR(75) null,student_contactName VARCHAR(75) null,student_contactRelationship VARCHAR(75) null,student_contactPhoneNumber VARCHAR(75) null,student_contactEmail VARCHAR(75) null,student_schoolName VARCHAR(75) null,student_schoolYear VARCHAR(75) null,student_academicLevel VARCHAR(75) null,student_studiedLanguage VARCHAR(75) null,student_languageCenter VARCHAR(75) null,student_prizes VARCHAR(75) null,student_skippedGrade VARCHAR(75) null,student_penalty VARCHAR(75) null,student_interests VARCHAR(75) null,student_note VARCHAR(75) null,student_registrationClass VARCHAR(75) null,student_expectedEnrollTime VARCHAR(75) null,student_userCar VARCHAR(75) null,student_theLightClub VARCHAR(75) null,student_oversea VARCHAR(75) null,student_howToKnowBM VARCHAR(75) null,student_whoIntroduce VARCHAR(75) null,student_anyConfuse VARCHAR(75) null,status VARCHAR(75) null,created_date DATE null,modified_date DATE null,deleted BOOLEAN)";
	public static final String TABLE_SQL_DROP = "drop table BN_PrimarySchoolStudent";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.fsoft.bn.model.PrimarySchoolStudent"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.fsoft.bn.model.PrimarySchoolStudent"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.fsoft.bn.model.PrimarySchoolStudent"));

	public PrimarySchoolStudentModelImpl() {
	}

	public String getPrimaryKey() {
		return _primaryStudent_id;
	}

	public void setPrimaryKey(String primaryKey) {
		setPrimaryStudent_id(primaryKey);
	}

	public Serializable getPrimaryKeyObj() {
		return _primaryStudent_id;
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey((String)primaryKeyObj);
	}

	public Class<?> getModelClass() {
		return PrimarySchoolStudent.class;
	}

	public String getModelClassName() {
		return PrimarySchoolStudent.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("primaryStudent_id", getPrimaryStudent_id());
		attributes.put("student_name", getStudent_name());
		attributes.put("student_sex", getStudent_sex());
		attributes.put("student_dob", getStudent_dob());
		attributes.put("student_placeOfBirth", getStudent_placeOfBirth());
		attributes.put("student_nationality", getStudent_nationality());
		attributes.put("student_address", getStudent_address());
		attributes.put("student_contactName", getStudent_contactName());
		attributes.put("student_contactRelationship",
			getStudent_contactRelationship());
		attributes.put("student_contactPhoneNumber",
			getStudent_contactPhoneNumber());
		attributes.put("student_contactEmail", getStudent_contactEmail());
		attributes.put("student_schoolName", getStudent_schoolName());
		attributes.put("student_schoolYear", getStudent_schoolYear());
		attributes.put("student_academicLevel", getStudent_academicLevel());
		attributes.put("student_studiedLanguage", getStudent_studiedLanguage());
		attributes.put("student_languageCenter", getStudent_languageCenter());
		attributes.put("student_prizes", getStudent_prizes());
		attributes.put("student_skippedGrade", getStudent_skippedGrade());
		attributes.put("student_penalty", getStudent_penalty());
		attributes.put("student_interests", getStudent_interests());
		attributes.put("student_note", getStudent_note());
		attributes.put("student_registrationClass",
			getStudent_registrationClass());
		attributes.put("student_expectedEnrollTime",
			getStudent_expectedEnrollTime());
		attributes.put("student_userCar", getStudent_userCar());
		attributes.put("student_theLightClub", getStudent_theLightClub());
		attributes.put("student_oversea", getStudent_oversea());
		attributes.put("student_howToKnowBM", getStudent_howToKnowBM());
		attributes.put("student_whoIntroduce", getStudent_whoIntroduce());
		attributes.put("student_anyConfuse", getStudent_anyConfuse());
		attributes.put("status", getStatus());
		attributes.put("created_date", getCreated_date());
		attributes.put("modified_date", getModified_date());
		attributes.put("deleted", getDeleted());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		String primaryStudent_id = (String)attributes.get("primaryStudent_id");

		if (primaryStudent_id != null) {
			setPrimaryStudent_id(primaryStudent_id);
		}

		String student_name = (String)attributes.get("student_name");

		if (student_name != null) {
			setStudent_name(student_name);
		}

		String student_sex = (String)attributes.get("student_sex");

		if (student_sex != null) {
			setStudent_sex(student_sex);
		}

		String student_dob = (String)attributes.get("student_dob");

		if (student_dob != null) {
			setStudent_dob(student_dob);
		}

		String student_placeOfBirth = (String)attributes.get(
				"student_placeOfBirth");

		if (student_placeOfBirth != null) {
			setStudent_placeOfBirth(student_placeOfBirth);
		}

		String student_nationality = (String)attributes.get(
				"student_nationality");

		if (student_nationality != null) {
			setStudent_nationality(student_nationality);
		}

		String student_address = (String)attributes.get("student_address");

		if (student_address != null) {
			setStudent_address(student_address);
		}

		String student_contactName = (String)attributes.get(
				"student_contactName");

		if (student_contactName != null) {
			setStudent_contactName(student_contactName);
		}

		String student_contactRelationship = (String)attributes.get(
				"student_contactRelationship");

		if (student_contactRelationship != null) {
			setStudent_contactRelationship(student_contactRelationship);
		}

		String student_contactPhoneNumber = (String)attributes.get(
				"student_contactPhoneNumber");

		if (student_contactPhoneNumber != null) {
			setStudent_contactPhoneNumber(student_contactPhoneNumber);
		}

		String student_contactEmail = (String)attributes.get(
				"student_contactEmail");

		if (student_contactEmail != null) {
			setStudent_contactEmail(student_contactEmail);
		}

		String student_schoolName = (String)attributes.get("student_schoolName");

		if (student_schoolName != null) {
			setStudent_schoolName(student_schoolName);
		}

		String student_schoolYear = (String)attributes.get("student_schoolYear");

		if (student_schoolYear != null) {
			setStudent_schoolYear(student_schoolYear);
		}

		String student_academicLevel = (String)attributes.get(
				"student_academicLevel");

		if (student_academicLevel != null) {
			setStudent_academicLevel(student_academicLevel);
		}

		String student_studiedLanguage = (String)attributes.get(
				"student_studiedLanguage");

		if (student_studiedLanguage != null) {
			setStudent_studiedLanguage(student_studiedLanguage);
		}

		String student_languageCenter = (String)attributes.get(
				"student_languageCenter");

		if (student_languageCenter != null) {
			setStudent_languageCenter(student_languageCenter);
		}

		String student_prizes = (String)attributes.get("student_prizes");

		if (student_prizes != null) {
			setStudent_prizes(student_prizes);
		}

		String student_skippedGrade = (String)attributes.get(
				"student_skippedGrade");

		if (student_skippedGrade != null) {
			setStudent_skippedGrade(student_skippedGrade);
		}

		String student_penalty = (String)attributes.get("student_penalty");

		if (student_penalty != null) {
			setStudent_penalty(student_penalty);
		}

		String student_interests = (String)attributes.get("student_interests");

		if (student_interests != null) {
			setStudent_interests(student_interests);
		}

		String student_note = (String)attributes.get("student_note");

		if (student_note != null) {
			setStudent_note(student_note);
		}

		String student_registrationClass = (String)attributes.get(
				"student_registrationClass");

		if (student_registrationClass != null) {
			setStudent_registrationClass(student_registrationClass);
		}

		String student_expectedEnrollTime = (String)attributes.get(
				"student_expectedEnrollTime");

		if (student_expectedEnrollTime != null) {
			setStudent_expectedEnrollTime(student_expectedEnrollTime);
		}

		String student_userCar = (String)attributes.get("student_userCar");

		if (student_userCar != null) {
			setStudent_userCar(student_userCar);
		}

		String student_theLightClub = (String)attributes.get(
				"student_theLightClub");

		if (student_theLightClub != null) {
			setStudent_theLightClub(student_theLightClub);
		}

		String student_oversea = (String)attributes.get("student_oversea");

		if (student_oversea != null) {
			setStudent_oversea(student_oversea);
		}

		String student_howToKnowBM = (String)attributes.get(
				"student_howToKnowBM");

		if (student_howToKnowBM != null) {
			setStudent_howToKnowBM(student_howToKnowBM);
		}

		String student_whoIntroduce = (String)attributes.get(
				"student_whoIntroduce");

		if (student_whoIntroduce != null) {
			setStudent_whoIntroduce(student_whoIntroduce);
		}

		String student_anyConfuse = (String)attributes.get("student_anyConfuse");

		if (student_anyConfuse != null) {
			setStudent_anyConfuse(student_anyConfuse);
		}

		String status = (String)attributes.get("status");

		if (status != null) {
			setStatus(status);
		}

		Date created_date = (Date)attributes.get("created_date");

		if (created_date != null) {
			setCreated_date(created_date);
		}

		Date modified_date = (Date)attributes.get("modified_date");

		if (modified_date != null) {
			setModified_date(modified_date);
		}

		Boolean deleted = (Boolean)attributes.get("deleted");

		if (deleted != null) {
			setDeleted(deleted);
		}
	}

	public String getPrimaryStudent_id() {
		if (_primaryStudent_id == null) {
			return StringPool.BLANK;
		}
		else {
			return _primaryStudent_id;
		}
	}

	public void setPrimaryStudent_id(String primaryStudent_id) {
		_primaryStudent_id = primaryStudent_id;
	}

	public String getStudent_name() {
		if (_student_name == null) {
			return StringPool.BLANK;
		}
		else {
			return _student_name;
		}
	}

	public void setStudent_name(String student_name) {
		_student_name = student_name;
	}

	public String getStudent_sex() {
		if (_student_sex == null) {
			return StringPool.BLANK;
		}
		else {
			return _student_sex;
		}
	}

	public void setStudent_sex(String student_sex) {
		_student_sex = student_sex;
	}

	public String getStudent_dob() {
		if (_student_dob == null) {
			return StringPool.BLANK;
		}
		else {
			return _student_dob;
		}
	}

	public void setStudent_dob(String student_dob) {
		_student_dob = student_dob;
	}

	public String getStudent_placeOfBirth() {
		if (_student_placeOfBirth == null) {
			return StringPool.BLANK;
		}
		else {
			return _student_placeOfBirth;
		}
	}

	public void setStudent_placeOfBirth(String student_placeOfBirth) {
		_student_placeOfBirth = student_placeOfBirth;
	}

	public String getStudent_nationality() {
		if (_student_nationality == null) {
			return StringPool.BLANK;
		}
		else {
			return _student_nationality;
		}
	}

	public void setStudent_nationality(String student_nationality) {
		_student_nationality = student_nationality;
	}

	public String getStudent_address() {
		if (_student_address == null) {
			return StringPool.BLANK;
		}
		else {
			return _student_address;
		}
	}

	public void setStudent_address(String student_address) {
		_student_address = student_address;
	}

	public String getStudent_contactName() {
		if (_student_contactName == null) {
			return StringPool.BLANK;
		}
		else {
			return _student_contactName;
		}
	}

	public void setStudent_contactName(String student_contactName) {
		_student_contactName = student_contactName;
	}

	public String getStudent_contactRelationship() {
		if (_student_contactRelationship == null) {
			return StringPool.BLANK;
		}
		else {
			return _student_contactRelationship;
		}
	}

	public void setStudent_contactRelationship(
		String student_contactRelationship) {
		_student_contactRelationship = student_contactRelationship;
	}

	public String getStudent_contactPhoneNumber() {
		if (_student_contactPhoneNumber == null) {
			return StringPool.BLANK;
		}
		else {
			return _student_contactPhoneNumber;
		}
	}

	public void setStudent_contactPhoneNumber(String student_contactPhoneNumber) {
		_student_contactPhoneNumber = student_contactPhoneNumber;
	}

	public String getStudent_contactEmail() {
		if (_student_contactEmail == null) {
			return StringPool.BLANK;
		}
		else {
			return _student_contactEmail;
		}
	}

	public void setStudent_contactEmail(String student_contactEmail) {
		_student_contactEmail = student_contactEmail;
	}

	public String getStudent_schoolName() {
		if (_student_schoolName == null) {
			return StringPool.BLANK;
		}
		else {
			return _student_schoolName;
		}
	}

	public void setStudent_schoolName(String student_schoolName) {
		_student_schoolName = student_schoolName;
	}

	public String getStudent_schoolYear() {
		if (_student_schoolYear == null) {
			return StringPool.BLANK;
		}
		else {
			return _student_schoolYear;
		}
	}

	public void setStudent_schoolYear(String student_schoolYear) {
		_student_schoolYear = student_schoolYear;
	}

	public String getStudent_academicLevel() {
		if (_student_academicLevel == null) {
			return StringPool.BLANK;
		}
		else {
			return _student_academicLevel;
		}
	}

	public void setStudent_academicLevel(String student_academicLevel) {
		_student_academicLevel = student_academicLevel;
	}

	public String getStudent_studiedLanguage() {
		if (_student_studiedLanguage == null) {
			return StringPool.BLANK;
		}
		else {
			return _student_studiedLanguage;
		}
	}

	public void setStudent_studiedLanguage(String student_studiedLanguage) {
		_student_studiedLanguage = student_studiedLanguage;
	}

	public String getStudent_languageCenter() {
		if (_student_languageCenter == null) {
			return StringPool.BLANK;
		}
		else {
			return _student_languageCenter;
		}
	}

	public void setStudent_languageCenter(String student_languageCenter) {
		_student_languageCenter = student_languageCenter;
	}

	public String getStudent_prizes() {
		if (_student_prizes == null) {
			return StringPool.BLANK;
		}
		else {
			return _student_prizes;
		}
	}

	public void setStudent_prizes(String student_prizes) {
		_student_prizes = student_prizes;
	}

	public String getStudent_skippedGrade() {
		if (_student_skippedGrade == null) {
			return StringPool.BLANK;
		}
		else {
			return _student_skippedGrade;
		}
	}

	public void setStudent_skippedGrade(String student_skippedGrade) {
		_student_skippedGrade = student_skippedGrade;
	}

	public String getStudent_penalty() {
		if (_student_penalty == null) {
			return StringPool.BLANK;
		}
		else {
			return _student_penalty;
		}
	}

	public void setStudent_penalty(String student_penalty) {
		_student_penalty = student_penalty;
	}

	public String getStudent_interests() {
		if (_student_interests == null) {
			return StringPool.BLANK;
		}
		else {
			return _student_interests;
		}
	}

	public void setStudent_interests(String student_interests) {
		_student_interests = student_interests;
	}

	public String getStudent_note() {
		if (_student_note == null) {
			return StringPool.BLANK;
		}
		else {
			return _student_note;
		}
	}

	public void setStudent_note(String student_note) {
		_student_note = student_note;
	}

	public String getStudent_registrationClass() {
		if (_student_registrationClass == null) {
			return StringPool.BLANK;
		}
		else {
			return _student_registrationClass;
		}
	}

	public void setStudent_registrationClass(String student_registrationClass) {
		_student_registrationClass = student_registrationClass;
	}

	public String getStudent_expectedEnrollTime() {
		if (_student_expectedEnrollTime == null) {
			return StringPool.BLANK;
		}
		else {
			return _student_expectedEnrollTime;
		}
	}

	public void setStudent_expectedEnrollTime(String student_expectedEnrollTime) {
		_student_expectedEnrollTime = student_expectedEnrollTime;
	}

	public String getStudent_userCar() {
		if (_student_userCar == null) {
			return StringPool.BLANK;
		}
		else {
			return _student_userCar;
		}
	}

	public void setStudent_userCar(String student_userCar) {
		_student_userCar = student_userCar;
	}

	public String getStudent_theLightClub() {
		if (_student_theLightClub == null) {
			return StringPool.BLANK;
		}
		else {
			return _student_theLightClub;
		}
	}

	public void setStudent_theLightClub(String student_theLightClub) {
		_student_theLightClub = student_theLightClub;
	}

	public String getStudent_oversea() {
		if (_student_oversea == null) {
			return StringPool.BLANK;
		}
		else {
			return _student_oversea;
		}
	}

	public void setStudent_oversea(String student_oversea) {
		_student_oversea = student_oversea;
	}

	public String getStudent_howToKnowBM() {
		if (_student_howToKnowBM == null) {
			return StringPool.BLANK;
		}
		else {
			return _student_howToKnowBM;
		}
	}

	public void setStudent_howToKnowBM(String student_howToKnowBM) {
		_student_howToKnowBM = student_howToKnowBM;
	}

	public String getStudent_whoIntroduce() {
		if (_student_whoIntroduce == null) {
			return StringPool.BLANK;
		}
		else {
			return _student_whoIntroduce;
		}
	}

	public void setStudent_whoIntroduce(String student_whoIntroduce) {
		_student_whoIntroduce = student_whoIntroduce;
	}

	public String getStudent_anyConfuse() {
		if (_student_anyConfuse == null) {
			return StringPool.BLANK;
		}
		else {
			return _student_anyConfuse;
		}
	}

	public void setStudent_anyConfuse(String student_anyConfuse) {
		_student_anyConfuse = student_anyConfuse;
	}

	public String getStatus() {
		if (_status == null) {
			return StringPool.BLANK;
		}
		else {
			return _status;
		}
	}

	public void setStatus(String status) {
		_status = status;
	}

	public Date getCreated_date() {
		return _created_date;
	}

	public void setCreated_date(Date created_date) {
		_created_date = created_date;
	}

	public Date getModified_date() {
		return _modified_date;
	}

	public void setModified_date(Date modified_date) {
		_modified_date = modified_date;
	}

	public boolean getDeleted() {
		return _deleted;
	}

	public boolean isDeleted() {
		return _deleted;
	}

	public void setDeleted(boolean deleted) {
		_deleted = deleted;
	}

	@Override
	public PrimarySchoolStudent toEscapedModel() {
		if (_escapedModelProxy == null) {
			_escapedModelProxy = (PrimarySchoolStudent)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelProxyInterfaces,
					new AutoEscapeBeanHandler(this));
		}

		return _escapedModelProxy;
	}

	@Override
	public Object clone() {
		PrimarySchoolStudentImpl primarySchoolStudentImpl = new PrimarySchoolStudentImpl();

		primarySchoolStudentImpl.setPrimaryStudent_id(getPrimaryStudent_id());
		primarySchoolStudentImpl.setStudent_name(getStudent_name());
		primarySchoolStudentImpl.setStudent_sex(getStudent_sex());
		primarySchoolStudentImpl.setStudent_dob(getStudent_dob());
		primarySchoolStudentImpl.setStudent_placeOfBirth(getStudent_placeOfBirth());
		primarySchoolStudentImpl.setStudent_nationality(getStudent_nationality());
		primarySchoolStudentImpl.setStudent_address(getStudent_address());
		primarySchoolStudentImpl.setStudent_contactName(getStudent_contactName());
		primarySchoolStudentImpl.setStudent_contactRelationship(getStudent_contactRelationship());
		primarySchoolStudentImpl.setStudent_contactPhoneNumber(getStudent_contactPhoneNumber());
		primarySchoolStudentImpl.setStudent_contactEmail(getStudent_contactEmail());
		primarySchoolStudentImpl.setStudent_schoolName(getStudent_schoolName());
		primarySchoolStudentImpl.setStudent_schoolYear(getStudent_schoolYear());
		primarySchoolStudentImpl.setStudent_academicLevel(getStudent_academicLevel());
		primarySchoolStudentImpl.setStudent_studiedLanguage(getStudent_studiedLanguage());
		primarySchoolStudentImpl.setStudent_languageCenter(getStudent_languageCenter());
		primarySchoolStudentImpl.setStudent_prizes(getStudent_prizes());
		primarySchoolStudentImpl.setStudent_skippedGrade(getStudent_skippedGrade());
		primarySchoolStudentImpl.setStudent_penalty(getStudent_penalty());
		primarySchoolStudentImpl.setStudent_interests(getStudent_interests());
		primarySchoolStudentImpl.setStudent_note(getStudent_note());
		primarySchoolStudentImpl.setStudent_registrationClass(getStudent_registrationClass());
		primarySchoolStudentImpl.setStudent_expectedEnrollTime(getStudent_expectedEnrollTime());
		primarySchoolStudentImpl.setStudent_userCar(getStudent_userCar());
		primarySchoolStudentImpl.setStudent_theLightClub(getStudent_theLightClub());
		primarySchoolStudentImpl.setStudent_oversea(getStudent_oversea());
		primarySchoolStudentImpl.setStudent_howToKnowBM(getStudent_howToKnowBM());
		primarySchoolStudentImpl.setStudent_whoIntroduce(getStudent_whoIntroduce());
		primarySchoolStudentImpl.setStudent_anyConfuse(getStudent_anyConfuse());
		primarySchoolStudentImpl.setStatus(getStatus());
		primarySchoolStudentImpl.setCreated_date(getCreated_date());
		primarySchoolStudentImpl.setModified_date(getModified_date());
		primarySchoolStudentImpl.setDeleted(getDeleted());

		primarySchoolStudentImpl.resetOriginalValues();

		return primarySchoolStudentImpl;
	}

	public int compareTo(PrimarySchoolStudent primarySchoolStudent) {
		String primaryKey = primarySchoolStudent.getPrimaryKey();

		return getPrimaryKey().compareTo(primaryKey);
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		PrimarySchoolStudent primarySchoolStudent = null;

		try {
			primarySchoolStudent = (PrimarySchoolStudent)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		String primaryKey = primarySchoolStudent.getPrimaryKey();

		if (getPrimaryKey().equals(primaryKey)) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey().hashCode();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<PrimarySchoolStudent> toCacheModel() {
		PrimarySchoolStudentCacheModel primarySchoolStudentCacheModel = new PrimarySchoolStudentCacheModel();

		primarySchoolStudentCacheModel.primaryStudent_id = getPrimaryStudent_id();

		String primaryStudent_id = primarySchoolStudentCacheModel.primaryStudent_id;

		if ((primaryStudent_id != null) && (primaryStudent_id.length() == 0)) {
			primarySchoolStudentCacheModel.primaryStudent_id = null;
		}

		primarySchoolStudentCacheModel.student_name = getStudent_name();

		String student_name = primarySchoolStudentCacheModel.student_name;

		if ((student_name != null) && (student_name.length() == 0)) {
			primarySchoolStudentCacheModel.student_name = null;
		}

		primarySchoolStudentCacheModel.student_sex = getStudent_sex();

		String student_sex = primarySchoolStudentCacheModel.student_sex;

		if ((student_sex != null) && (student_sex.length() == 0)) {
			primarySchoolStudentCacheModel.student_sex = null;
		}

		primarySchoolStudentCacheModel.student_dob = getStudent_dob();

		String student_dob = primarySchoolStudentCacheModel.student_dob;

		if ((student_dob != null) && (student_dob.length() == 0)) {
			primarySchoolStudentCacheModel.student_dob = null;
		}

		primarySchoolStudentCacheModel.student_placeOfBirth = getStudent_placeOfBirth();

		String student_placeOfBirth = primarySchoolStudentCacheModel.student_placeOfBirth;

		if ((student_placeOfBirth != null) &&
				(student_placeOfBirth.length() == 0)) {
			primarySchoolStudentCacheModel.student_placeOfBirth = null;
		}

		primarySchoolStudentCacheModel.student_nationality = getStudent_nationality();

		String student_nationality = primarySchoolStudentCacheModel.student_nationality;

		if ((student_nationality != null) &&
				(student_nationality.length() == 0)) {
			primarySchoolStudentCacheModel.student_nationality = null;
		}

		primarySchoolStudentCacheModel.student_address = getStudent_address();

		String student_address = primarySchoolStudentCacheModel.student_address;

		if ((student_address != null) && (student_address.length() == 0)) {
			primarySchoolStudentCacheModel.student_address = null;
		}

		primarySchoolStudentCacheModel.student_contactName = getStudent_contactName();

		String student_contactName = primarySchoolStudentCacheModel.student_contactName;

		if ((student_contactName != null) &&
				(student_contactName.length() == 0)) {
			primarySchoolStudentCacheModel.student_contactName = null;
		}

		primarySchoolStudentCacheModel.student_contactRelationship = getStudent_contactRelationship();

		String student_contactRelationship = primarySchoolStudentCacheModel.student_contactRelationship;

		if ((student_contactRelationship != null) &&
				(student_contactRelationship.length() == 0)) {
			primarySchoolStudentCacheModel.student_contactRelationship = null;
		}

		primarySchoolStudentCacheModel.student_contactPhoneNumber = getStudent_contactPhoneNumber();

		String student_contactPhoneNumber = primarySchoolStudentCacheModel.student_contactPhoneNumber;

		if ((student_contactPhoneNumber != null) &&
				(student_contactPhoneNumber.length() == 0)) {
			primarySchoolStudentCacheModel.student_contactPhoneNumber = null;
		}

		primarySchoolStudentCacheModel.student_contactEmail = getStudent_contactEmail();

		String student_contactEmail = primarySchoolStudentCacheModel.student_contactEmail;

		if ((student_contactEmail != null) &&
				(student_contactEmail.length() == 0)) {
			primarySchoolStudentCacheModel.student_contactEmail = null;
		}

		primarySchoolStudentCacheModel.student_schoolName = getStudent_schoolName();

		String student_schoolName = primarySchoolStudentCacheModel.student_schoolName;

		if ((student_schoolName != null) && (student_schoolName.length() == 0)) {
			primarySchoolStudentCacheModel.student_schoolName = null;
		}

		primarySchoolStudentCacheModel.student_schoolYear = getStudent_schoolYear();

		String student_schoolYear = primarySchoolStudentCacheModel.student_schoolYear;

		if ((student_schoolYear != null) && (student_schoolYear.length() == 0)) {
			primarySchoolStudentCacheModel.student_schoolYear = null;
		}

		primarySchoolStudentCacheModel.student_academicLevel = getStudent_academicLevel();

		String student_academicLevel = primarySchoolStudentCacheModel.student_academicLevel;

		if ((student_academicLevel != null) &&
				(student_academicLevel.length() == 0)) {
			primarySchoolStudentCacheModel.student_academicLevel = null;
		}

		primarySchoolStudentCacheModel.student_studiedLanguage = getStudent_studiedLanguage();

		String student_studiedLanguage = primarySchoolStudentCacheModel.student_studiedLanguage;

		if ((student_studiedLanguage != null) &&
				(student_studiedLanguage.length() == 0)) {
			primarySchoolStudentCacheModel.student_studiedLanguage = null;
		}

		primarySchoolStudentCacheModel.student_languageCenter = getStudent_languageCenter();

		String student_languageCenter = primarySchoolStudentCacheModel.student_languageCenter;

		if ((student_languageCenter != null) &&
				(student_languageCenter.length() == 0)) {
			primarySchoolStudentCacheModel.student_languageCenter = null;
		}

		primarySchoolStudentCacheModel.student_prizes = getStudent_prizes();

		String student_prizes = primarySchoolStudentCacheModel.student_prizes;

		if ((student_prizes != null) && (student_prizes.length() == 0)) {
			primarySchoolStudentCacheModel.student_prizes = null;
		}

		primarySchoolStudentCacheModel.student_skippedGrade = getStudent_skippedGrade();

		String student_skippedGrade = primarySchoolStudentCacheModel.student_skippedGrade;

		if ((student_skippedGrade != null) &&
				(student_skippedGrade.length() == 0)) {
			primarySchoolStudentCacheModel.student_skippedGrade = null;
		}

		primarySchoolStudentCacheModel.student_penalty = getStudent_penalty();

		String student_penalty = primarySchoolStudentCacheModel.student_penalty;

		if ((student_penalty != null) && (student_penalty.length() == 0)) {
			primarySchoolStudentCacheModel.student_penalty = null;
		}

		primarySchoolStudentCacheModel.student_interests = getStudent_interests();

		String student_interests = primarySchoolStudentCacheModel.student_interests;

		if ((student_interests != null) && (student_interests.length() == 0)) {
			primarySchoolStudentCacheModel.student_interests = null;
		}

		primarySchoolStudentCacheModel.student_note = getStudent_note();

		String student_note = primarySchoolStudentCacheModel.student_note;

		if ((student_note != null) && (student_note.length() == 0)) {
			primarySchoolStudentCacheModel.student_note = null;
		}

		primarySchoolStudentCacheModel.student_registrationClass = getStudent_registrationClass();

		String student_registrationClass = primarySchoolStudentCacheModel.student_registrationClass;

		if ((student_registrationClass != null) &&
				(student_registrationClass.length() == 0)) {
			primarySchoolStudentCacheModel.student_registrationClass = null;
		}

		primarySchoolStudentCacheModel.student_expectedEnrollTime = getStudent_expectedEnrollTime();

		String student_expectedEnrollTime = primarySchoolStudentCacheModel.student_expectedEnrollTime;

		if ((student_expectedEnrollTime != null) &&
				(student_expectedEnrollTime.length() == 0)) {
			primarySchoolStudentCacheModel.student_expectedEnrollTime = null;
		}

		primarySchoolStudentCacheModel.student_userCar = getStudent_userCar();

		String student_userCar = primarySchoolStudentCacheModel.student_userCar;

		if ((student_userCar != null) && (student_userCar.length() == 0)) {
			primarySchoolStudentCacheModel.student_userCar = null;
		}

		primarySchoolStudentCacheModel.student_theLightClub = getStudent_theLightClub();

		String student_theLightClub = primarySchoolStudentCacheModel.student_theLightClub;

		if ((student_theLightClub != null) &&
				(student_theLightClub.length() == 0)) {
			primarySchoolStudentCacheModel.student_theLightClub = null;
		}

		primarySchoolStudentCacheModel.student_oversea = getStudent_oversea();

		String student_oversea = primarySchoolStudentCacheModel.student_oversea;

		if ((student_oversea != null) && (student_oversea.length() == 0)) {
			primarySchoolStudentCacheModel.student_oversea = null;
		}

		primarySchoolStudentCacheModel.student_howToKnowBM = getStudent_howToKnowBM();

		String student_howToKnowBM = primarySchoolStudentCacheModel.student_howToKnowBM;

		if ((student_howToKnowBM != null) &&
				(student_howToKnowBM.length() == 0)) {
			primarySchoolStudentCacheModel.student_howToKnowBM = null;
		}

		primarySchoolStudentCacheModel.student_whoIntroduce = getStudent_whoIntroduce();

		String student_whoIntroduce = primarySchoolStudentCacheModel.student_whoIntroduce;

		if ((student_whoIntroduce != null) &&
				(student_whoIntroduce.length() == 0)) {
			primarySchoolStudentCacheModel.student_whoIntroduce = null;
		}

		primarySchoolStudentCacheModel.student_anyConfuse = getStudent_anyConfuse();

		String student_anyConfuse = primarySchoolStudentCacheModel.student_anyConfuse;

		if ((student_anyConfuse != null) && (student_anyConfuse.length() == 0)) {
			primarySchoolStudentCacheModel.student_anyConfuse = null;
		}

		primarySchoolStudentCacheModel.status = getStatus();

		String status = primarySchoolStudentCacheModel.status;

		if ((status != null) && (status.length() == 0)) {
			primarySchoolStudentCacheModel.status = null;
		}

		Date created_date = getCreated_date();

		if (created_date != null) {
			primarySchoolStudentCacheModel.created_date = created_date.getTime();
		}
		else {
			primarySchoolStudentCacheModel.created_date = Long.MIN_VALUE;
		}

		Date modified_date = getModified_date();

		if (modified_date != null) {
			primarySchoolStudentCacheModel.modified_date = modified_date.getTime();
		}
		else {
			primarySchoolStudentCacheModel.modified_date = Long.MIN_VALUE;
		}

		primarySchoolStudentCacheModel.deleted = getDeleted();

		return primarySchoolStudentCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(67);

		sb.append("{primaryStudent_id=");
		sb.append(getPrimaryStudent_id());
		sb.append(", student_name=");
		sb.append(getStudent_name());
		sb.append(", student_sex=");
		sb.append(getStudent_sex());
		sb.append(", student_dob=");
		sb.append(getStudent_dob());
		sb.append(", student_placeOfBirth=");
		sb.append(getStudent_placeOfBirth());
		sb.append(", student_nationality=");
		sb.append(getStudent_nationality());
		sb.append(", student_address=");
		sb.append(getStudent_address());
		sb.append(", student_contactName=");
		sb.append(getStudent_contactName());
		sb.append(", student_contactRelationship=");
		sb.append(getStudent_contactRelationship());
		sb.append(", student_contactPhoneNumber=");
		sb.append(getStudent_contactPhoneNumber());
		sb.append(", student_contactEmail=");
		sb.append(getStudent_contactEmail());
		sb.append(", student_schoolName=");
		sb.append(getStudent_schoolName());
		sb.append(", student_schoolYear=");
		sb.append(getStudent_schoolYear());
		sb.append(", student_academicLevel=");
		sb.append(getStudent_academicLevel());
		sb.append(", student_studiedLanguage=");
		sb.append(getStudent_studiedLanguage());
		sb.append(", student_languageCenter=");
		sb.append(getStudent_languageCenter());
		sb.append(", student_prizes=");
		sb.append(getStudent_prizes());
		sb.append(", student_skippedGrade=");
		sb.append(getStudent_skippedGrade());
		sb.append(", student_penalty=");
		sb.append(getStudent_penalty());
		sb.append(", student_interests=");
		sb.append(getStudent_interests());
		sb.append(", student_note=");
		sb.append(getStudent_note());
		sb.append(", student_registrationClass=");
		sb.append(getStudent_registrationClass());
		sb.append(", student_expectedEnrollTime=");
		sb.append(getStudent_expectedEnrollTime());
		sb.append(", student_userCar=");
		sb.append(getStudent_userCar());
		sb.append(", student_theLightClub=");
		sb.append(getStudent_theLightClub());
		sb.append(", student_oversea=");
		sb.append(getStudent_oversea());
		sb.append(", student_howToKnowBM=");
		sb.append(getStudent_howToKnowBM());
		sb.append(", student_whoIntroduce=");
		sb.append(getStudent_whoIntroduce());
		sb.append(", student_anyConfuse=");
		sb.append(getStudent_anyConfuse());
		sb.append(", status=");
		sb.append(getStatus());
		sb.append(", created_date=");
		sb.append(getCreated_date());
		sb.append(", modified_date=");
		sb.append(getModified_date());
		sb.append(", deleted=");
		sb.append(getDeleted());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(103);

		sb.append("<model><model-name>");
		sb.append("com.fsoft.bn.model.PrimarySchoolStudent");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>primaryStudent_id</column-name><column-value><![CDATA[");
		sb.append(getPrimaryStudent_id());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>student_name</column-name><column-value><![CDATA[");
		sb.append(getStudent_name());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>student_sex</column-name><column-value><![CDATA[");
		sb.append(getStudent_sex());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>student_dob</column-name><column-value><![CDATA[");
		sb.append(getStudent_dob());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>student_placeOfBirth</column-name><column-value><![CDATA[");
		sb.append(getStudent_placeOfBirth());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>student_nationality</column-name><column-value><![CDATA[");
		sb.append(getStudent_nationality());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>student_address</column-name><column-value><![CDATA[");
		sb.append(getStudent_address());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>student_contactName</column-name><column-value><![CDATA[");
		sb.append(getStudent_contactName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>student_contactRelationship</column-name><column-value><![CDATA[");
		sb.append(getStudent_contactRelationship());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>student_contactPhoneNumber</column-name><column-value><![CDATA[");
		sb.append(getStudent_contactPhoneNumber());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>student_contactEmail</column-name><column-value><![CDATA[");
		sb.append(getStudent_contactEmail());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>student_schoolName</column-name><column-value><![CDATA[");
		sb.append(getStudent_schoolName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>student_schoolYear</column-name><column-value><![CDATA[");
		sb.append(getStudent_schoolYear());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>student_academicLevel</column-name><column-value><![CDATA[");
		sb.append(getStudent_academicLevel());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>student_studiedLanguage</column-name><column-value><![CDATA[");
		sb.append(getStudent_studiedLanguage());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>student_languageCenter</column-name><column-value><![CDATA[");
		sb.append(getStudent_languageCenter());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>student_prizes</column-name><column-value><![CDATA[");
		sb.append(getStudent_prizes());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>student_skippedGrade</column-name><column-value><![CDATA[");
		sb.append(getStudent_skippedGrade());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>student_penalty</column-name><column-value><![CDATA[");
		sb.append(getStudent_penalty());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>student_interests</column-name><column-value><![CDATA[");
		sb.append(getStudent_interests());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>student_note</column-name><column-value><![CDATA[");
		sb.append(getStudent_note());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>student_registrationClass</column-name><column-value><![CDATA[");
		sb.append(getStudent_registrationClass());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>student_expectedEnrollTime</column-name><column-value><![CDATA[");
		sb.append(getStudent_expectedEnrollTime());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>student_userCar</column-name><column-value><![CDATA[");
		sb.append(getStudent_userCar());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>student_theLightClub</column-name><column-value><![CDATA[");
		sb.append(getStudent_theLightClub());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>student_oversea</column-name><column-value><![CDATA[");
		sb.append(getStudent_oversea());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>student_howToKnowBM</column-name><column-value><![CDATA[");
		sb.append(getStudent_howToKnowBM());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>student_whoIntroduce</column-name><column-value><![CDATA[");
		sb.append(getStudent_whoIntroduce());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>student_anyConfuse</column-name><column-value><![CDATA[");
		sb.append(getStudent_anyConfuse());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>status</column-name><column-value><![CDATA[");
		sb.append(getStatus());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>created_date</column-name><column-value><![CDATA[");
		sb.append(getCreated_date());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modified_date</column-name><column-value><![CDATA[");
		sb.append(getModified_date());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>deleted</column-name><column-value><![CDATA[");
		sb.append(getDeleted());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = PrimarySchoolStudent.class.getClassLoader();
	private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
			PrimarySchoolStudent.class
		};
	private String _primaryStudent_id;
	private String _student_name;
	private String _student_sex;
	private String _student_dob;
	private String _student_placeOfBirth;
	private String _student_nationality;
	private String _student_address;
	private String _student_contactName;
	private String _student_contactRelationship;
	private String _student_contactPhoneNumber;
	private String _student_contactEmail;
	private String _student_schoolName;
	private String _student_schoolYear;
	private String _student_academicLevel;
	private String _student_studiedLanguage;
	private String _student_languageCenter;
	private String _student_prizes;
	private String _student_skippedGrade;
	private String _student_penalty;
	private String _student_interests;
	private String _student_note;
	private String _student_registrationClass;
	private String _student_expectedEnrollTime;
	private String _student_userCar;
	private String _student_theLightClub;
	private String _student_oversea;
	private String _student_howToKnowBM;
	private String _student_whoIntroduce;
	private String _student_anyConfuse;
	private String _status;
	private Date _created_date;
	private Date _modified_date;
	private boolean _deleted;
	private PrimarySchoolStudent _escapedModelProxy;
}