/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.fsoft.bn.model.impl;

import com.fsoft.bn.model.RecruitmentLanguages;
import com.fsoft.bn.model.RecruitmentLanguagesModel;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the RecruitmentLanguages service. Represents a row in the &quot;BN_RecruitmentLanguages&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.fsoft.bn.model.RecruitmentLanguagesModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link RecruitmentLanguagesImpl}.
 * </p>
 *
 * @author FSOFT
 * @see RecruitmentLanguagesImpl
 * @see com.fsoft.bn.model.RecruitmentLanguages
 * @see com.fsoft.bn.model.RecruitmentLanguagesModel
 * @generated
 */
public class RecruitmentLanguagesModelImpl extends BaseModelImpl<RecruitmentLanguages>
	implements RecruitmentLanguagesModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a recruitment languages model instance should use the {@link com.fsoft.bn.model.RecruitmentLanguages} interface instead.
	 */
	public static final String TABLE_NAME = "BN_RecruitmentLanguages";
	public static final Object[][] TABLE_COLUMNS = {
			{ "recruitment_languages_id", Types.VARCHAR },
			{ "recruitment_id", Types.VARCHAR },
			{ "language", Types.VARCHAR },
			{ "level", Types.VARCHAR },
			{ "certificate", Types.VARCHAR },
			{ "created_date", Types.TIMESTAMP },
			{ "modified_date", Types.TIMESTAMP },
			{ "deleted", Types.BOOLEAN }
		};
	public static final String TABLE_SQL_CREATE = "create table BN_RecruitmentLanguages (recruitment_languages_id VARCHAR(75) not null primary key,recruitment_id VARCHAR(75) null,language VARCHAR(75) null,level VARCHAR(75) null,certificate VARCHAR(75) null,created_date DATE null,modified_date DATE null,deleted BOOLEAN)";
	public static final String TABLE_SQL_DROP = "drop table BN_RecruitmentLanguages";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.fsoft.bn.model.RecruitmentLanguages"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.fsoft.bn.model.RecruitmentLanguages"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.fsoft.bn.model.RecruitmentLanguages"));

	public RecruitmentLanguagesModelImpl() {
	}

	public String getPrimaryKey() {
		return _recruitment_languages_id;
	}

	public void setPrimaryKey(String primaryKey) {
		setRecruitment_languages_id(primaryKey);
	}

	public Serializable getPrimaryKeyObj() {
		return _recruitment_languages_id;
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey((String)primaryKeyObj);
	}

	public Class<?> getModelClass() {
		return RecruitmentLanguages.class;
	}

	public String getModelClassName() {
		return RecruitmentLanguages.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("recruitment_languages_id", getRecruitment_languages_id());
		attributes.put("recruitment_id", getRecruitment_id());
		attributes.put("language", getLanguage());
		attributes.put("level", getLevel());
		attributes.put("certificate", getCertificate());
		attributes.put("created_date", getCreated_date());
		attributes.put("modified_date", getModified_date());
		attributes.put("deleted", getDeleted());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		String recruitment_languages_id = (String)attributes.get(
				"recruitment_languages_id");

		if (recruitment_languages_id != null) {
			setRecruitment_languages_id(recruitment_languages_id);
		}

		String recruitment_id = (String)attributes.get("recruitment_id");

		if (recruitment_id != null) {
			setRecruitment_id(recruitment_id);
		}

		String language = (String)attributes.get("language");

		if (language != null) {
			setLanguage(language);
		}

		String level = (String)attributes.get("level");

		if (level != null) {
			setLevel(level);
		}

		String certificate = (String)attributes.get("certificate");

		if (certificate != null) {
			setCertificate(certificate);
		}

		Date created_date = (Date)attributes.get("created_date");

		if (created_date != null) {
			setCreated_date(created_date);
		}

		Date modified_date = (Date)attributes.get("modified_date");

		if (modified_date != null) {
			setModified_date(modified_date);
		}

		Boolean deleted = (Boolean)attributes.get("deleted");

		if (deleted != null) {
			setDeleted(deleted);
		}
	}

	public String getRecruitment_languages_id() {
		if (_recruitment_languages_id == null) {
			return StringPool.BLANK;
		}
		else {
			return _recruitment_languages_id;
		}
	}

	public void setRecruitment_languages_id(String recruitment_languages_id) {
		_recruitment_languages_id = recruitment_languages_id;
	}

	public String getRecruitment_id() {
		if (_recruitment_id == null) {
			return StringPool.BLANK;
		}
		else {
			return _recruitment_id;
		}
	}

	public void setRecruitment_id(String recruitment_id) {
		_recruitment_id = recruitment_id;
	}

	public String getLanguage() {
		if (_language == null) {
			return StringPool.BLANK;
		}
		else {
			return _language;
		}
	}

	public void setLanguage(String language) {
		_language = language;
	}

	public String getLevel() {
		if (_level == null) {
			return StringPool.BLANK;
		}
		else {
			return _level;
		}
	}

	public void setLevel(String level) {
		_level = level;
	}

	public String getCertificate() {
		if (_certificate == null) {
			return StringPool.BLANK;
		}
		else {
			return _certificate;
		}
	}

	public void setCertificate(String certificate) {
		_certificate = certificate;
	}

	public Date getCreated_date() {
		return _created_date;
	}

	public void setCreated_date(Date created_date) {
		_created_date = created_date;
	}

	public Date getModified_date() {
		return _modified_date;
	}

	public void setModified_date(Date modified_date) {
		_modified_date = modified_date;
	}

	public boolean getDeleted() {
		return _deleted;
	}

	public boolean isDeleted() {
		return _deleted;
	}

	public void setDeleted(boolean deleted) {
		_deleted = deleted;
	}

	@Override
	public RecruitmentLanguages toEscapedModel() {
		if (_escapedModelProxy == null) {
			_escapedModelProxy = (RecruitmentLanguages)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelProxyInterfaces,
					new AutoEscapeBeanHandler(this));
		}

		return _escapedModelProxy;
	}

	@Override
	public Object clone() {
		RecruitmentLanguagesImpl recruitmentLanguagesImpl = new RecruitmentLanguagesImpl();

		recruitmentLanguagesImpl.setRecruitment_languages_id(getRecruitment_languages_id());
		recruitmentLanguagesImpl.setRecruitment_id(getRecruitment_id());
		recruitmentLanguagesImpl.setLanguage(getLanguage());
		recruitmentLanguagesImpl.setLevel(getLevel());
		recruitmentLanguagesImpl.setCertificate(getCertificate());
		recruitmentLanguagesImpl.setCreated_date(getCreated_date());
		recruitmentLanguagesImpl.setModified_date(getModified_date());
		recruitmentLanguagesImpl.setDeleted(getDeleted());

		recruitmentLanguagesImpl.resetOriginalValues();

		return recruitmentLanguagesImpl;
	}

	public int compareTo(RecruitmentLanguages recruitmentLanguages) {
		String primaryKey = recruitmentLanguages.getPrimaryKey();

		return getPrimaryKey().compareTo(primaryKey);
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		RecruitmentLanguages recruitmentLanguages = null;

		try {
			recruitmentLanguages = (RecruitmentLanguages)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		String primaryKey = recruitmentLanguages.getPrimaryKey();

		if (getPrimaryKey().equals(primaryKey)) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey().hashCode();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<RecruitmentLanguages> toCacheModel() {
		RecruitmentLanguagesCacheModel recruitmentLanguagesCacheModel = new RecruitmentLanguagesCacheModel();

		recruitmentLanguagesCacheModel.recruitment_languages_id = getRecruitment_languages_id();

		String recruitment_languages_id = recruitmentLanguagesCacheModel.recruitment_languages_id;

		if ((recruitment_languages_id != null) &&
				(recruitment_languages_id.length() == 0)) {
			recruitmentLanguagesCacheModel.recruitment_languages_id = null;
		}

		recruitmentLanguagesCacheModel.recruitment_id = getRecruitment_id();

		String recruitment_id = recruitmentLanguagesCacheModel.recruitment_id;

		if ((recruitment_id != null) && (recruitment_id.length() == 0)) {
			recruitmentLanguagesCacheModel.recruitment_id = null;
		}

		recruitmentLanguagesCacheModel.language = getLanguage();

		String language = recruitmentLanguagesCacheModel.language;

		if ((language != null) && (language.length() == 0)) {
			recruitmentLanguagesCacheModel.language = null;
		}

		recruitmentLanguagesCacheModel.level = getLevel();

		String level = recruitmentLanguagesCacheModel.level;

		if ((level != null) && (level.length() == 0)) {
			recruitmentLanguagesCacheModel.level = null;
		}

		recruitmentLanguagesCacheModel.certificate = getCertificate();

		String certificate = recruitmentLanguagesCacheModel.certificate;

		if ((certificate != null) && (certificate.length() == 0)) {
			recruitmentLanguagesCacheModel.certificate = null;
		}

		Date created_date = getCreated_date();

		if (created_date != null) {
			recruitmentLanguagesCacheModel.created_date = created_date.getTime();
		}
		else {
			recruitmentLanguagesCacheModel.created_date = Long.MIN_VALUE;
		}

		Date modified_date = getModified_date();

		if (modified_date != null) {
			recruitmentLanguagesCacheModel.modified_date = modified_date.getTime();
		}
		else {
			recruitmentLanguagesCacheModel.modified_date = Long.MIN_VALUE;
		}

		recruitmentLanguagesCacheModel.deleted = getDeleted();

		return recruitmentLanguagesCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(17);

		sb.append("{recruitment_languages_id=");
		sb.append(getRecruitment_languages_id());
		sb.append(", recruitment_id=");
		sb.append(getRecruitment_id());
		sb.append(", language=");
		sb.append(getLanguage());
		sb.append(", level=");
		sb.append(getLevel());
		sb.append(", certificate=");
		sb.append(getCertificate());
		sb.append(", created_date=");
		sb.append(getCreated_date());
		sb.append(", modified_date=");
		sb.append(getModified_date());
		sb.append(", deleted=");
		sb.append(getDeleted());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(28);

		sb.append("<model><model-name>");
		sb.append("com.fsoft.bn.model.RecruitmentLanguages");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>recruitment_languages_id</column-name><column-value><![CDATA[");
		sb.append(getRecruitment_languages_id());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>recruitment_id</column-name><column-value><![CDATA[");
		sb.append(getRecruitment_id());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>language</column-name><column-value><![CDATA[");
		sb.append(getLanguage());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>level</column-name><column-value><![CDATA[");
		sb.append(getLevel());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>certificate</column-name><column-value><![CDATA[");
		sb.append(getCertificate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>created_date</column-name><column-value><![CDATA[");
		sb.append(getCreated_date());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modified_date</column-name><column-value><![CDATA[");
		sb.append(getModified_date());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>deleted</column-name><column-value><![CDATA[");
		sb.append(getDeleted());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = RecruitmentLanguages.class.getClassLoader();
	private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
			RecruitmentLanguages.class
		};
	private String _recruitment_languages_id;
	private String _recruitment_id;
	private String _language;
	private String _level;
	private String _certificate;
	private Date _created_date;
	private Date _modified_date;
	private boolean _deleted;
	private RecruitmentLanguages _escapedModelProxy;
}