/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.fsoft.bn.model.impl;

import com.fsoft.bn.model.RecruitmentTrainingCourses;
import com.fsoft.bn.model.RecruitmentTrainingCoursesModel;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the RecruitmentTrainingCourses service. Represents a row in the &quot;BN_RecruitmentTrainingCourses&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.fsoft.bn.model.RecruitmentTrainingCoursesModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link RecruitmentTrainingCoursesImpl}.
 * </p>
 *
 * @author FSOFT
 * @see RecruitmentTrainingCoursesImpl
 * @see com.fsoft.bn.model.RecruitmentTrainingCourses
 * @see com.fsoft.bn.model.RecruitmentTrainingCoursesModel
 * @generated
 */
public class RecruitmentTrainingCoursesModelImpl extends BaseModelImpl<RecruitmentTrainingCourses>
	implements RecruitmentTrainingCoursesModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a recruitment training courses model instance should use the {@link com.fsoft.bn.model.RecruitmentTrainingCourses} interface instead.
	 */
	public static final String TABLE_NAME = "BN_RecruitmentTrainingCourses";
	public static final Object[][] TABLE_COLUMNS = {
			{ "recruitment_training_courses_id", Types.VARCHAR },
			{ "recruitment_id", Types.VARCHAR },
			{ "conductedBy", Types.VARCHAR },
			{ "courseName", Types.VARCHAR },
			{ "courseDesc", Types.VARCHAR },
			{ "courseDate", Types.VARCHAR },
			{ "certificate", Types.VARCHAR },
			{ "created_date", Types.TIMESTAMP },
			{ "modified_date", Types.TIMESTAMP },
			{ "deleted", Types.BOOLEAN }
		};
	public static final String TABLE_SQL_CREATE = "create table BN_RecruitmentTrainingCourses (recruitment_training_courses_id VARCHAR(75) not null primary key,recruitment_id VARCHAR(75) null,conductedBy VARCHAR(75) null,courseName VARCHAR(75) null,courseDesc VARCHAR(75) null,courseDate VARCHAR(75) null,certificate VARCHAR(75) null,created_date DATE null,modified_date DATE null,deleted BOOLEAN)";
	public static final String TABLE_SQL_DROP = "drop table BN_RecruitmentTrainingCourses";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.fsoft.bn.model.RecruitmentTrainingCourses"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.fsoft.bn.model.RecruitmentTrainingCourses"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.fsoft.bn.model.RecruitmentTrainingCourses"));

	public RecruitmentTrainingCoursesModelImpl() {
	}

	public String getPrimaryKey() {
		return _recruitment_training_courses_id;
	}

	public void setPrimaryKey(String primaryKey) {
		setRecruitment_training_courses_id(primaryKey);
	}

	public Serializable getPrimaryKeyObj() {
		return _recruitment_training_courses_id;
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey((String)primaryKeyObj);
	}

	public Class<?> getModelClass() {
		return RecruitmentTrainingCourses.class;
	}

	public String getModelClassName() {
		return RecruitmentTrainingCourses.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("recruitment_training_courses_id",
			getRecruitment_training_courses_id());
		attributes.put("recruitment_id", getRecruitment_id());
		attributes.put("conductedBy", getConductedBy());
		attributes.put("courseName", getCourseName());
		attributes.put("courseDesc", getCourseDesc());
		attributes.put("courseDate", getCourseDate());
		attributes.put("certificate", getCertificate());
		attributes.put("created_date", getCreated_date());
		attributes.put("modified_date", getModified_date());
		attributes.put("deleted", getDeleted());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		String recruitment_training_courses_id = (String)attributes.get(
				"recruitment_training_courses_id");

		if (recruitment_training_courses_id != null) {
			setRecruitment_training_courses_id(recruitment_training_courses_id);
		}

		String recruitment_id = (String)attributes.get("recruitment_id");

		if (recruitment_id != null) {
			setRecruitment_id(recruitment_id);
		}

		String conductedBy = (String)attributes.get("conductedBy");

		if (conductedBy != null) {
			setConductedBy(conductedBy);
		}

		String courseName = (String)attributes.get("courseName");

		if (courseName != null) {
			setCourseName(courseName);
		}

		String courseDesc = (String)attributes.get("courseDesc");

		if (courseDesc != null) {
			setCourseDesc(courseDesc);
		}

		String courseDate = (String)attributes.get("courseDate");

		if (courseDate != null) {
			setCourseDate(courseDate);
		}

		String certificate = (String)attributes.get("certificate");

		if (certificate != null) {
			setCertificate(certificate);
		}

		Date created_date = (Date)attributes.get("created_date");

		if (created_date != null) {
			setCreated_date(created_date);
		}

		Date modified_date = (Date)attributes.get("modified_date");

		if (modified_date != null) {
			setModified_date(modified_date);
		}

		Boolean deleted = (Boolean)attributes.get("deleted");

		if (deleted != null) {
			setDeleted(deleted);
		}
	}

	public String getRecruitment_training_courses_id() {
		if (_recruitment_training_courses_id == null) {
			return StringPool.BLANK;
		}
		else {
			return _recruitment_training_courses_id;
		}
	}

	public void setRecruitment_training_courses_id(
		String recruitment_training_courses_id) {
		_recruitment_training_courses_id = recruitment_training_courses_id;
	}

	public String getRecruitment_id() {
		if (_recruitment_id == null) {
			return StringPool.BLANK;
		}
		else {
			return _recruitment_id;
		}
	}

	public void setRecruitment_id(String recruitment_id) {
		_recruitment_id = recruitment_id;
	}

	public String getConductedBy() {
		if (_conductedBy == null) {
			return StringPool.BLANK;
		}
		else {
			return _conductedBy;
		}
	}

	public void setConductedBy(String conductedBy) {
		_conductedBy = conductedBy;
	}

	public String getCourseName() {
		if (_courseName == null) {
			return StringPool.BLANK;
		}
		else {
			return _courseName;
		}
	}

	public void setCourseName(String courseName) {
		_courseName = courseName;
	}

	public String getCourseDesc() {
		if (_courseDesc == null) {
			return StringPool.BLANK;
		}
		else {
			return _courseDesc;
		}
	}

	public void setCourseDesc(String courseDesc) {
		_courseDesc = courseDesc;
	}

	public String getCourseDate() {
		if (_courseDate == null) {
			return StringPool.BLANK;
		}
		else {
			return _courseDate;
		}
	}

	public void setCourseDate(String courseDate) {
		_courseDate = courseDate;
	}

	public String getCertificate() {
		if (_certificate == null) {
			return StringPool.BLANK;
		}
		else {
			return _certificate;
		}
	}

	public void setCertificate(String certificate) {
		_certificate = certificate;
	}

	public Date getCreated_date() {
		return _created_date;
	}

	public void setCreated_date(Date created_date) {
		_created_date = created_date;
	}

	public Date getModified_date() {
		return _modified_date;
	}

	public void setModified_date(Date modified_date) {
		_modified_date = modified_date;
	}

	public boolean getDeleted() {
		return _deleted;
	}

	public boolean isDeleted() {
		return _deleted;
	}

	public void setDeleted(boolean deleted) {
		_deleted = deleted;
	}

	@Override
	public RecruitmentTrainingCourses toEscapedModel() {
		if (_escapedModelProxy == null) {
			_escapedModelProxy = (RecruitmentTrainingCourses)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelProxyInterfaces,
					new AutoEscapeBeanHandler(this));
		}

		return _escapedModelProxy;
	}

	@Override
	public Object clone() {
		RecruitmentTrainingCoursesImpl recruitmentTrainingCoursesImpl = new RecruitmentTrainingCoursesImpl();

		recruitmentTrainingCoursesImpl.setRecruitment_training_courses_id(getRecruitment_training_courses_id());
		recruitmentTrainingCoursesImpl.setRecruitment_id(getRecruitment_id());
		recruitmentTrainingCoursesImpl.setConductedBy(getConductedBy());
		recruitmentTrainingCoursesImpl.setCourseName(getCourseName());
		recruitmentTrainingCoursesImpl.setCourseDesc(getCourseDesc());
		recruitmentTrainingCoursesImpl.setCourseDate(getCourseDate());
		recruitmentTrainingCoursesImpl.setCertificate(getCertificate());
		recruitmentTrainingCoursesImpl.setCreated_date(getCreated_date());
		recruitmentTrainingCoursesImpl.setModified_date(getModified_date());
		recruitmentTrainingCoursesImpl.setDeleted(getDeleted());

		recruitmentTrainingCoursesImpl.resetOriginalValues();

		return recruitmentTrainingCoursesImpl;
	}

	public int compareTo(RecruitmentTrainingCourses recruitmentTrainingCourses) {
		String primaryKey = recruitmentTrainingCourses.getPrimaryKey();

		return getPrimaryKey().compareTo(primaryKey);
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		RecruitmentTrainingCourses recruitmentTrainingCourses = null;

		try {
			recruitmentTrainingCourses = (RecruitmentTrainingCourses)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		String primaryKey = recruitmentTrainingCourses.getPrimaryKey();

		if (getPrimaryKey().equals(primaryKey)) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey().hashCode();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<RecruitmentTrainingCourses> toCacheModel() {
		RecruitmentTrainingCoursesCacheModel recruitmentTrainingCoursesCacheModel =
			new RecruitmentTrainingCoursesCacheModel();

		recruitmentTrainingCoursesCacheModel.recruitment_training_courses_id = getRecruitment_training_courses_id();

		String recruitment_training_courses_id = recruitmentTrainingCoursesCacheModel.recruitment_training_courses_id;

		if ((recruitment_training_courses_id != null) &&
				(recruitment_training_courses_id.length() == 0)) {
			recruitmentTrainingCoursesCacheModel.recruitment_training_courses_id = null;
		}

		recruitmentTrainingCoursesCacheModel.recruitment_id = getRecruitment_id();

		String recruitment_id = recruitmentTrainingCoursesCacheModel.recruitment_id;

		if ((recruitment_id != null) && (recruitment_id.length() == 0)) {
			recruitmentTrainingCoursesCacheModel.recruitment_id = null;
		}

		recruitmentTrainingCoursesCacheModel.conductedBy = getConductedBy();

		String conductedBy = recruitmentTrainingCoursesCacheModel.conductedBy;

		if ((conductedBy != null) && (conductedBy.length() == 0)) {
			recruitmentTrainingCoursesCacheModel.conductedBy = null;
		}

		recruitmentTrainingCoursesCacheModel.courseName = getCourseName();

		String courseName = recruitmentTrainingCoursesCacheModel.courseName;

		if ((courseName != null) && (courseName.length() == 0)) {
			recruitmentTrainingCoursesCacheModel.courseName = null;
		}

		recruitmentTrainingCoursesCacheModel.courseDesc = getCourseDesc();

		String courseDesc = recruitmentTrainingCoursesCacheModel.courseDesc;

		if ((courseDesc != null) && (courseDesc.length() == 0)) {
			recruitmentTrainingCoursesCacheModel.courseDesc = null;
		}

		recruitmentTrainingCoursesCacheModel.courseDate = getCourseDate();

		String courseDate = recruitmentTrainingCoursesCacheModel.courseDate;

		if ((courseDate != null) && (courseDate.length() == 0)) {
			recruitmentTrainingCoursesCacheModel.courseDate = null;
		}

		recruitmentTrainingCoursesCacheModel.certificate = getCertificate();

		String certificate = recruitmentTrainingCoursesCacheModel.certificate;

		if ((certificate != null) && (certificate.length() == 0)) {
			recruitmentTrainingCoursesCacheModel.certificate = null;
		}

		Date created_date = getCreated_date();

		if (created_date != null) {
			recruitmentTrainingCoursesCacheModel.created_date = created_date.getTime();
		}
		else {
			recruitmentTrainingCoursesCacheModel.created_date = Long.MIN_VALUE;
		}

		Date modified_date = getModified_date();

		if (modified_date != null) {
			recruitmentTrainingCoursesCacheModel.modified_date = modified_date.getTime();
		}
		else {
			recruitmentTrainingCoursesCacheModel.modified_date = Long.MIN_VALUE;
		}

		recruitmentTrainingCoursesCacheModel.deleted = getDeleted();

		return recruitmentTrainingCoursesCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(21);

		sb.append("{recruitment_training_courses_id=");
		sb.append(getRecruitment_training_courses_id());
		sb.append(", recruitment_id=");
		sb.append(getRecruitment_id());
		sb.append(", conductedBy=");
		sb.append(getConductedBy());
		sb.append(", courseName=");
		sb.append(getCourseName());
		sb.append(", courseDesc=");
		sb.append(getCourseDesc());
		sb.append(", courseDate=");
		sb.append(getCourseDate());
		sb.append(", certificate=");
		sb.append(getCertificate());
		sb.append(", created_date=");
		sb.append(getCreated_date());
		sb.append(", modified_date=");
		sb.append(getModified_date());
		sb.append(", deleted=");
		sb.append(getDeleted());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(34);

		sb.append("<model><model-name>");
		sb.append("com.fsoft.bn.model.RecruitmentTrainingCourses");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>recruitment_training_courses_id</column-name><column-value><![CDATA[");
		sb.append(getRecruitment_training_courses_id());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>recruitment_id</column-name><column-value><![CDATA[");
		sb.append(getRecruitment_id());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>conductedBy</column-name><column-value><![CDATA[");
		sb.append(getConductedBy());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>courseName</column-name><column-value><![CDATA[");
		sb.append(getCourseName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>courseDesc</column-name><column-value><![CDATA[");
		sb.append(getCourseDesc());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>courseDate</column-name><column-value><![CDATA[");
		sb.append(getCourseDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>certificate</column-name><column-value><![CDATA[");
		sb.append(getCertificate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>created_date</column-name><column-value><![CDATA[");
		sb.append(getCreated_date());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modified_date</column-name><column-value><![CDATA[");
		sb.append(getModified_date());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>deleted</column-name><column-value><![CDATA[");
		sb.append(getDeleted());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = RecruitmentTrainingCourses.class.getClassLoader();
	private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
			RecruitmentTrainingCourses.class
		};
	private String _recruitment_training_courses_id;
	private String _recruitment_id;
	private String _conductedBy;
	private String _courseName;
	private String _courseDesc;
	private String _courseDate;
	private String _certificate;
	private Date _created_date;
	private Date _modified_date;
	private boolean _deleted;
	private RecruitmentTrainingCourses _escapedModelProxy;
}