/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.fsoft.bn.model.impl;

import com.fsoft.bn.model.Answer;
import com.fsoft.bn.model.AnswerModel;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the Answer service. Represents a row in the &quot;BN_Answer&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.fsoft.bn.model.AnswerModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link AnswerImpl}.
 * </p>
 *
 * @author FSOFT
 * @see AnswerImpl
 * @see com.fsoft.bn.model.Answer
 * @see com.fsoft.bn.model.AnswerModel
 * @generated
 */
public class AnswerModelImpl extends BaseModelImpl<Answer>
	implements AnswerModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a answer model instance should use the {@link com.fsoft.bn.model.Answer} interface instead.
	 */
	public static final String TABLE_NAME = "BN_Answer";
	public static final Object[][] TABLE_COLUMNS = {
			{ "answer_id", Types.VARCHAR },
			{ "answer_content", Types.VARCHAR },
			{ "user_id", Types.VARCHAR },
			{ "created_date", Types.TIMESTAMP },
			{ "modified_date", Types.TIMESTAMP },
			{ "deleted", Types.BOOLEAN }
		};
	public static final String TABLE_SQL_CREATE = "create table BN_Answer (answer_id VARCHAR(75) not null primary key,answer_content STRING null,user_id VARCHAR(75) null,created_date DATE null,modified_date DATE null,deleted BOOLEAN)";
	public static final String TABLE_SQL_DROP = "drop table BN_Answer";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.fsoft.bn.model.Answer"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.fsoft.bn.model.Answer"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.fsoft.bn.model.Answer"));

	public AnswerModelImpl() {
	}

	public String getPrimaryKey() {
		return _answer_id;
	}

	public void setPrimaryKey(String primaryKey) {
		setAnswer_id(primaryKey);
	}

	public Serializable getPrimaryKeyObj() {
		return _answer_id;
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey((String)primaryKeyObj);
	}

	public Class<?> getModelClass() {
		return Answer.class;
	}

	public String getModelClassName() {
		return Answer.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("answer_id", getAnswer_id());
		attributes.put("answer_content", getAnswer_content());
		attributes.put("user_id", getUser_id());
		attributes.put("created_date", getCreated_date());
		attributes.put("modified_date", getModified_date());
		attributes.put("deleted", getDeleted());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		String answer_id = (String)attributes.get("answer_id");

		if (answer_id != null) {
			setAnswer_id(answer_id);
		}

		String answer_content = (String)attributes.get("answer_content");

		if (answer_content != null) {
			setAnswer_content(answer_content);
		}

		String user_id = (String)attributes.get("user_id");

		if (user_id != null) {
			setUser_id(user_id);
		}

		Date created_date = (Date)attributes.get("created_date");

		if (created_date != null) {
			setCreated_date(created_date);
		}

		Date modified_date = (Date)attributes.get("modified_date");

		if (modified_date != null) {
			setModified_date(modified_date);
		}

		Boolean deleted = (Boolean)attributes.get("deleted");

		if (deleted != null) {
			setDeleted(deleted);
		}
	}

	public String getAnswer_id() {
		if (_answer_id == null) {
			return StringPool.BLANK;
		}
		else {
			return _answer_id;
		}
	}

	public void setAnswer_id(String answer_id) {
		_answer_id = answer_id;
	}

	public String getAnswer_content() {
		if (_answer_content == null) {
			return StringPool.BLANK;
		}
		else {
			return _answer_content;
		}
	}

	public void setAnswer_content(String answer_content) {
		_answer_content = answer_content;
	}

	public String getUser_id() {
		if (_user_id == null) {
			return StringPool.BLANK;
		}
		else {
			return _user_id;
		}
	}

	public void setUser_id(String user_id) {
		_user_id = user_id;
	}

	public Date getCreated_date() {
		return _created_date;
	}

	public void setCreated_date(Date created_date) {
		_created_date = created_date;
	}

	public Date getModified_date() {
		return _modified_date;
	}

	public void setModified_date(Date modified_date) {
		_modified_date = modified_date;
	}

	public boolean getDeleted() {
		return _deleted;
	}

	public boolean isDeleted() {
		return _deleted;
	}

	public void setDeleted(boolean deleted) {
		_deleted = deleted;
	}

	@Override
	public Answer toEscapedModel() {
		if (_escapedModelProxy == null) {
			_escapedModelProxy = (Answer)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelProxyInterfaces,
					new AutoEscapeBeanHandler(this));
		}

		return _escapedModelProxy;
	}

	@Override
	public Object clone() {
		AnswerImpl answerImpl = new AnswerImpl();

		answerImpl.setAnswer_id(getAnswer_id());
		answerImpl.setAnswer_content(getAnswer_content());
		answerImpl.setUser_id(getUser_id());
		answerImpl.setCreated_date(getCreated_date());
		answerImpl.setModified_date(getModified_date());
		answerImpl.setDeleted(getDeleted());

		answerImpl.resetOriginalValues();

		return answerImpl;
	}

	public int compareTo(Answer answer) {
		String primaryKey = answer.getPrimaryKey();

		return getPrimaryKey().compareTo(primaryKey);
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		Answer answer = null;

		try {
			answer = (Answer)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		String primaryKey = answer.getPrimaryKey();

		if (getPrimaryKey().equals(primaryKey)) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey().hashCode();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<Answer> toCacheModel() {
		AnswerCacheModel answerCacheModel = new AnswerCacheModel();

		answerCacheModel.answer_id = getAnswer_id();

		String answer_id = answerCacheModel.answer_id;

		if ((answer_id != null) && (answer_id.length() == 0)) {
			answerCacheModel.answer_id = null;
		}

		answerCacheModel.answer_content = getAnswer_content();

		String answer_content = answerCacheModel.answer_content;

		if ((answer_content != null) && (answer_content.length() == 0)) {
			answerCacheModel.answer_content = null;
		}

		answerCacheModel.user_id = getUser_id();

		String user_id = answerCacheModel.user_id;

		if ((user_id != null) && (user_id.length() == 0)) {
			answerCacheModel.user_id = null;
		}

		Date created_date = getCreated_date();

		if (created_date != null) {
			answerCacheModel.created_date = created_date.getTime();
		}
		else {
			answerCacheModel.created_date = Long.MIN_VALUE;
		}

		Date modified_date = getModified_date();

		if (modified_date != null) {
			answerCacheModel.modified_date = modified_date.getTime();
		}
		else {
			answerCacheModel.modified_date = Long.MIN_VALUE;
		}

		answerCacheModel.deleted = getDeleted();

		return answerCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(13);

		sb.append("{answer_id=");
		sb.append(getAnswer_id());
		sb.append(", answer_content=");
		sb.append(getAnswer_content());
		sb.append(", user_id=");
		sb.append(getUser_id());
		sb.append(", created_date=");
		sb.append(getCreated_date());
		sb.append(", modified_date=");
		sb.append(getModified_date());
		sb.append(", deleted=");
		sb.append(getDeleted());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(22);

		sb.append("<model><model-name>");
		sb.append("com.fsoft.bn.model.Answer");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>answer_id</column-name><column-value><![CDATA[");
		sb.append(getAnswer_id());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>answer_content</column-name><column-value><![CDATA[");
		sb.append(getAnswer_content());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>user_id</column-name><column-value><![CDATA[");
		sb.append(getUser_id());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>created_date</column-name><column-value><![CDATA[");
		sb.append(getCreated_date());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modified_date</column-name><column-value><![CDATA[");
		sb.append(getModified_date());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>deleted</column-name><column-value><![CDATA[");
		sb.append(getDeleted());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = Answer.class.getClassLoader();
	private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
			Answer.class
		};
	private String _answer_id;
	private String _answer_content;
	private String _user_id;
	private Date _created_date;
	private Date _modified_date;
	private boolean _deleted;
	private Answer _escapedModelProxy;
}