/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.fsoft.bn.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the BNNews service. Represents a row in the &quot;BN_BNNews&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.fsoft.bn.model.impl.BNNewsModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.fsoft.bn.model.impl.BNNewsImpl}.
 * </p>
 *
 * @author FSOFT
 * @see BNNews
 * @see com.fsoft.bn.model.impl.BNNewsImpl
 * @see com.fsoft.bn.model.impl.BNNewsModelImpl
 * @generated
 */
public interface BNNewsModel extends BaseModel<BNNews> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a b n news model instance should use the {@link BNNews} interface instead.
	 */

	/**
	 * Returns the primary key of this b n news.
	 *
	 * @return the primary key of this b n news
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this b n news.
	 *
	 * @param primaryKey the primary key of this b n news
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the news ID of this b n news.
	 *
	 * @return the news ID of this b n news
	 */
	public long getNewsId();

	/**
	 * Sets the news ID of this b n news.
	 *
	 * @param newsId the news ID of this b n news
	 */
	public void setNewsId(long newsId);

	/**
	 * Returns the news title of this b n news.
	 *
	 * @return the news title of this b n news
	 */
	@AutoEscape
	public String getNewsTitle();

	/**
	 * Sets the news title of this b n news.
	 *
	 * @param newsTitle the news title of this b n news
	 */
	public void setNewsTitle(String newsTitle);

	/**
	 * Returns the news content of this b n news.
	 *
	 * @return the news content of this b n news
	 */
	@AutoEscape
	public String getNewsContent();

	/**
	 * Sets the news content of this b n news.
	 *
	 * @param newsContent the news content of this b n news
	 */
	public void setNewsContent(String newsContent);

	/**
	 * Returns the created date of this b n news.
	 *
	 * @return the created date of this b n news
	 */
	public Date getCreatedDate();

	/**
	 * Sets the created date of this b n news.
	 *
	 * @param createdDate the created date of this b n news
	 */
	public void setCreatedDate(Date createdDate);

	/**
	 * Returns the modified date of this b n news.
	 *
	 * @return the modified date of this b n news
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this b n news.
	 *
	 * @param modifiedDate the modified date of this b n news
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the deleted of this b n news.
	 *
	 * @return the deleted of this b n news
	 */
	public boolean getDeleted();

	/**
	 * Returns <code>true</code> if this b n news is deleted.
	 *
	 * @return <code>true</code> if this b n news is deleted; <code>false</code> otherwise
	 */
	public boolean isDeleted();

	/**
	 * Sets whether this b n news is deleted.
	 *
	 * @param deleted the deleted of this b n news
	 */
	public void setDeleted(boolean deleted);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(BNNews bnNews);

	public int hashCode();

	public CacheModel<BNNews> toCacheModel();

	public BNNews toEscapedModel();

	public String toString();

	public String toXmlString();
}